// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repo

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Employee struct {
	ID         int64              `json:"id"`
	EmployeeID string             `json:"employee_id"`
	FullName   string             `json:"full_name"`
	Email      string             `json:"email"`
	Username   string             `json:"username"`
	Password   []byte             `json:"password"`
	Role       string             `json:"role"`
	IsActive   bool               `json:"is_active"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

type PasswordResetToken struct {
	ID         int64              `json:"id"`
	EmployeeID int64              `json:"employee_id"`
	TokenHash  string             `json:"token_hash"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
	UsedAt     pgtype.Timestamptz `json:"used_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}
