// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repo

import (
	"net"
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

type Employee struct {
	ID                  int64              `json:"id"`
	OdooEmployeeID      int64              `json:"odoo_employee_id"`
	FullName            string             `json:"full_name"`
	Email               string             `json:"email"`
	Username            string             `json:"username"`
	Password            []byte             `json:"password"`
	IsActive            bool               `json:"is_active"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
	FailedLoginAttempts int32              `json:"failed_login_attempts"`
	LockedUntil         pgtype.Timestamptz `json:"locked_until"`
}

type EmployeePosition struct {
	EmployeeID int64 `json:"employee_id"`
	PositionID int64 `json:"position_id"`
}

type EmployeeStore struct {
	EmployeeID int64 `json:"employee_id"`
	StoreID    int64 `json:"store_id"`
}

type PasswordResetToken struct {
	ID         int64              `json:"id"`
	EmployeeID int64              `json:"employee_id"`
	TokenHash  string             `json:"token_hash"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
	UsedAt     pgtype.Timestamptz `json:"used_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type Position struct {
	ID        int64              `json:"id"`
	Name      string             `json:"name"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type Session struct {
	ID                  int64              `json:"id"`
	EmployeeID          int64              `json:"employee_id"`
	StoreID             pgtype.Int8        `json:"store_id"`
	TokenHash           string             `json:"token_hash"`
	IssuedAt            pgtype.Timestamptz `json:"issued_at"`
	ExpiresAt           pgtype.Timestamptz `json:"expires_at"`
	LastHeartbeatAt     pgtype.Timestamptz `json:"last_heartbeat_at"`
	ConsecutiveFailures int32              `json:"consecutive_failures"`
}

type Store struct {
	ID                   int64              `json:"id"`
	OdooStoreID          pgtype.Text        `json:"odoo_store_id"`
	StoreName            string             `json:"store_name"`
	City                 pgtype.Text        `json:"city"`
	Latitude             pgtype.Numeric     `json:"latitude"`
	Longitude            pgtype.Numeric     `json:"longitude"`
	RadiusMeters         pgtype.Int4        `json:"radius_meters"`
	WifiWhitelistEnabled bool               `json:"wifi_whitelist_enabled"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
}

type StoreWifiIp struct {
	ID        int64              `json:"id"`
	StoreID   int64              `json:"store_id"`
	IpAddress netip.Addr         `json:"ip_address"`
	Label     pgtype.Text        `json:"label"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type StoreWifiMac struct {
	ID         int64              `json:"id"`
	StoreID    int64              `json:"store_id"`
	MacAddress net.HardwareAddr   `json:"mac_address"`
	Label      pgtype.Text        `json:"label"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}
