// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package repo

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createEmployee = `-- name: CreateEmployee :one
INSERT INTO employees (employee_id, full_name, email, username, role)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, employee_id, full_name, email, username, password, role, is_active, created_at, updated_at
`

type CreateEmployeeParams struct {
	EmployeeID string `json:"employee_id"`
	FullName   string `json:"full_name"`
	Email      string `json:"email"`
	Username   string `json:"username"`
	Role       string `json:"role"`
}

func (q *Queries) CreateEmployee(ctx context.Context, arg CreateEmployeeParams) (Employee, error) {
	row := q.db.QueryRow(ctx, createEmployee,
		arg.EmployeeID,
		arg.FullName,
		arg.Email,
		arg.Username,
		arg.Role,
	)
	var i Employee
	err := row.Scan(
		&i.ID,
		&i.EmployeeID,
		&i.FullName,
		&i.Email,
		&i.Username,
		&i.Password,
		&i.Role,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createPasswordResetToken = `-- name: CreatePasswordResetToken :one
INSERT INTO password_reset_tokens (employee_id, token, expires_at)
VALUES ($1, $2, $3)
RETURNING id, employee_id, token, expires_at, used_at, created_at
`

type CreatePasswordResetTokenParams struct {
	EmployeeID int64              `json:"employee_id"`
	Token      string             `json:"token"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreatePasswordResetToken(ctx context.Context, arg CreatePasswordResetTokenParams) (PasswordResetToken, error) {
	row := q.db.QueryRow(ctx, createPasswordResetToken, arg.EmployeeID, arg.Token, arg.ExpiresAt)
	var i PasswordResetToken
	err := row.Scan(
		&i.ID,
		&i.EmployeeID,
		&i.Token,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteEmployee = `-- name: DeleteEmployee :execrows
DELETE FROM employees
WHERE id = $1
`

func (q *Queries) DeleteEmployee(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, deleteEmployee, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getEmployeeByEmail = `-- name: GetEmployeeByEmail :one
SELECT id, employee_id, full_name, email, username, password, role, is_active, created_at, updated_at FROM employees
WHERE email = $1
`

func (q *Queries) GetEmployeeByEmail(ctx context.Context, email string) (Employee, error) {
	row := q.db.QueryRow(ctx, getEmployeeByEmail, email)
	var i Employee
	err := row.Scan(
		&i.ID,
		&i.EmployeeID,
		&i.FullName,
		&i.Email,
		&i.Username,
		&i.Password,
		&i.Role,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getEmployeeByID = `-- name: GetEmployeeByID :one
SELECT id, employee_id, full_name, email, username, password, role, is_active, created_at, updated_at FROM employees
WHERE id = $1
`

func (q *Queries) GetEmployeeByID(ctx context.Context, id int64) (Employee, error) {
	row := q.db.QueryRow(ctx, getEmployeeByID, id)
	var i Employee
	err := row.Scan(
		&i.ID,
		&i.EmployeeID,
		&i.FullName,
		&i.Email,
		&i.Username,
		&i.Password,
		&i.Role,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getEmployeeByUsername = `-- name: GetEmployeeByUsername :one
SELECT id, employee_id, full_name, email, username, password, role, is_active, created_at, updated_at FROM employees
WHERE username = $1
`

func (q *Queries) GetEmployeeByUsername(ctx context.Context, username string) (Employee, error) {
	row := q.db.QueryRow(ctx, getEmployeeByUsername, username)
	var i Employee
	err := row.Scan(
		&i.ID,
		&i.EmployeeID,
		&i.FullName,
		&i.Email,
		&i.Username,
		&i.Password,
		&i.Role,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listEmployees = `-- name: ListEmployees :many
SELECT id, employee_id, full_name, email, username, password, role, is_active, created_at, updated_at FROM employees
ORDER BY id
`

func (q *Queries) ListEmployees(ctx context.Context) ([]Employee, error) {
	rows, err := q.db.Query(ctx, listEmployees)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Employee
	for rows.Next() {
		var i Employee
		if err := rows.Scan(
			&i.ID,
			&i.EmployeeID,
			&i.FullName,
			&i.Email,
			&i.Username,
			&i.Password,
			&i.Role,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const redeemPasswordResetToken = `-- name: RedeemPasswordResetToken :one
UPDATE password_reset_tokens
SET used_at = now()
WHERE token = $1
  AND used_at IS NULL
  AND expires_at > now()
RETURNING id, employee_id, token, expires_at, used_at, created_at
`

// Atomically claims a valid, unused token: the UPDATE's row lock ensures
// only one concurrent caller can match the WHERE clause and get a row back,
// so CompleteActivation can't be raced into redeeming the same token twice.
func (q *Queries) RedeemPasswordResetToken(ctx context.Context, token string) (PasswordResetToken, error) {
	row := q.db.QueryRow(ctx, redeemPasswordResetToken, token)
	var i PasswordResetToken
	err := row.Scan(
		&i.ID,
		&i.EmployeeID,
		&i.Token,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const setEmployeeActive = `-- name: SetEmployeeActive :execrows
UPDATE employees
SET is_active = $2,
    updated_at = now()
WHERE id = $1
`

type SetEmployeeActiveParams struct {
	ID       int64 `json:"id"`
	IsActive bool  `json:"is_active"`
}

func (q *Queries) SetEmployeeActive(ctx context.Context, arg SetEmployeeActiveParams) (int64, error) {
	result, err := q.db.Exec(ctx, setEmployeeActive, arg.ID, arg.IsActive)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setEmployeePassword = `-- name: SetEmployeePassword :execrows
UPDATE employees
SET password = $2,
    updated_at = now()
WHERE id = $1
`

type SetEmployeePasswordParams struct {
	ID       int64  `json:"id"`
	Password []byte `json:"password"`
}

func (q *Queries) SetEmployeePassword(ctx context.Context, arg SetEmployeePasswordParams) (int64, error) {
	result, err := q.db.Exec(ctx, setEmployeePassword, arg.ID, arg.Password)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateEmployee = `-- name: UpdateEmployee :one
UPDATE employees
SET employee_id = $2,
    full_name = $3,
    email = $4,
    username = $5,
    role = $6,
    updated_at = now()
WHERE id = $1
RETURNING id, employee_id, full_name, email, username, password, role, is_active, created_at, updated_at
`

type UpdateEmployeeParams struct {
	ID         int64  `json:"id"`
	EmployeeID string `json:"employee_id"`
	FullName   string `json:"full_name"`
	Email      string `json:"email"`
	Username   string `json:"username"`
	Role       string `json:"role"`
}

func (q *Queries) UpdateEmployee(ctx context.Context, arg UpdateEmployeeParams) (Employee, error) {
	row := q.db.QueryRow(ctx, updateEmployee,
		arg.ID,
		arg.EmployeeID,
		arg.FullName,
		arg.Email,
		arg.Username,
		arg.Role,
	)
	var i Employee
	err := row.Scan(
		&i.ID,
		&i.EmployeeID,
		&i.FullName,
		&i.Email,
		&i.Username,
		&i.Password,
		&i.Role,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
