// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repo

import (
	"context"
)

type Querier interface {
	CreateEmployee(ctx context.Context, arg CreateEmployeeParams) (Employee, error)
	CreatePasswordResetToken(ctx context.Context, arg CreatePasswordResetTokenParams) (PasswordResetToken, error)
	DeleteEmployee(ctx context.Context, id int64) (int64, error)
	GetEmployeeByEmail(ctx context.Context, email string) (Employee, error)
	GetEmployeeByID(ctx context.Context, id int64) (Employee, error)
	GetEmployeeByUsername(ctx context.Context, username string) (Employee, error)
	GetValidPasswordResetToken(ctx context.Context, token string) (PasswordResetToken, error)
	ListEmployees(ctx context.Context) ([]Employee, error)
	MarkPasswordResetTokenUsed(ctx context.Context, id int64) error
	SetEmployeeActive(ctx context.Context, arg SetEmployeeActiveParams) (int64, error)
	SetEmployeePassword(ctx context.Context, arg SetEmployeePasswordParams) (int64, error)
	UpdateEmployee(ctx context.Context, arg UpdateEmployeeParams) (Employee, error)
}

var _ Querier = (*Queries)(nil)
