// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package repo

import (
	"context"
	"net"
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

const bulkSetStoreWifiWhitelistEnabled = `-- name: BulkSetStoreWifiWhitelistEnabled :many
UPDATE store
SET wifi_whitelist_enabled = $1,
    updated_at = now()
WHERE id = ANY($2::bigint[])
RETURNING id, wifi_whitelist_enabled, updated_at
`

type BulkSetStoreWifiWhitelistEnabledParams struct {
	WifiWhitelistEnabled bool    `json:"wifi_whitelist_enabled"`
	StoreIds             []int64 `json:"store_ids"`
}

type BulkSetStoreWifiWhitelistEnabledRow struct {
	ID                   int64              `json:"id"`
	WifiWhitelistEnabled bool               `json:"wifi_whitelist_enabled"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
}

// Applies the bulk PATCH /v1/stores write once GetStoresByIDsForUpdate has
// confirmed every id exists and every updated_at matched — see ADR-0006.
// RETURNING fresh state for every affected store so the handler can build
// the success response without a follow-up fetch.
func (q *Queries) BulkSetStoreWifiWhitelistEnabled(ctx context.Context, arg BulkSetStoreWifiWhitelistEnabledParams) ([]BulkSetStoreWifiWhitelistEnabledRow, error) {
	rows, err := q.db.Query(ctx, bulkSetStoreWifiWhitelistEnabled, arg.WifiWhitelistEnabled, arg.StoreIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BulkSetStoreWifiWhitelistEnabledRow
	for rows.Next() {
		var i BulkSetStoreWifiWhitelistEnabledRow
		if err := rows.Scan(&i.ID, &i.WifiWhitelistEnabled, &i.UpdatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countEmployeesByIDs = `-- name: CountEmployeesByIDs :one
SELECT count(*) FROM employees
WHERE id = ANY($1::bigint[])
`

// Position-first counterpart of CountPositionsByIDs: validates a submitted
// set of employee ids in one round trip for PUT /positions/{id}/employees
// (see ADR-0011) — a count short of the distinct submitted ids means at
// least one id isn't a real employee.
func (q *Queries) CountEmployeesByIDs(ctx context.Context, ids []int64) (int64, error) {
	row := q.db.QueryRow(ctx, countEmployeesByIDs, ids)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countPositionsByIDs = `-- name: CountPositionsByIDs :one
SELECT count(*) FROM positions
WHERE id = ANY($1::bigint[])
`

// Used to validate a submitted set of position ids in one round trip: if the
// count of matching rows is less than the count of distinct submitted ids,
// at least one id doesn't reference a real position (see ADR-0008 — this
// must be a clear client error, not a raw FK-violation 500).
func (q *Queries) CountPositionsByIDs(ctx context.Context, ids []int64) (int64, error) {
	row := q.db.QueryRow(ctx, countPositionsByIDs, ids)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createEmployee = `-- name: CreateEmployee :one
INSERT INTO employees (odoo_employee_id, full_name, email, username)
VALUES ($1, $2, $3, $4)
RETURNING id, odoo_employee_id, full_name, email, username, password, is_active, created_at, updated_at, failed_login_attempts, locked_until
`

type CreateEmployeeParams struct {
	OdooEmployeeID int64  `json:"odoo_employee_id"`
	FullName       string `json:"full_name"`
	Email          string `json:"email"`
	Username       string `json:"username"`
}

func (q *Queries) CreateEmployee(ctx context.Context, arg CreateEmployeeParams) (Employee, error) {
	row := q.db.QueryRow(ctx, createEmployee,
		arg.OdooEmployeeID,
		arg.FullName,
		arg.Email,
		arg.Username,
	)
	var i Employee
	err := row.Scan(
		&i.ID,
		&i.OdooEmployeeID,
		&i.FullName,
		&i.Email,
		&i.Username,
		&i.Password,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FailedLoginAttempts,
		&i.LockedUntil,
	)
	return i, err
}

const createPasswordResetToken = `-- name: CreatePasswordResetToken :one
INSERT INTO password_reset_tokens (employee_id, token_hash, expires_at)
VALUES ($1, $2, $3)
RETURNING id, employee_id, token_hash, expires_at, used_at, created_at
`

type CreatePasswordResetTokenParams struct {
	EmployeeID int64              `json:"employee_id"`
	TokenHash  string             `json:"token_hash"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreatePasswordResetToken(ctx context.Context, arg CreatePasswordResetTokenParams) (PasswordResetToken, error) {
	row := q.db.QueryRow(ctx, createPasswordResetToken, arg.EmployeeID, arg.TokenHash, arg.ExpiresAt)
	var i PasswordResetToken
	err := row.Scan(
		&i.ID,
		&i.EmployeeID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const createPosition = `-- name: CreatePosition :one
INSERT INTO positions (name)
VALUES ($1)
RETURNING id, name, created_at, updated_at
`

func (q *Queries) CreatePosition(ctx context.Context, name string) (Position, error) {
	row := q.db.QueryRow(ctx, createPosition, name)
	var i Position
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteEmployee = `-- name: DeleteEmployee :execrows
DELETE FROM employees
WHERE id = $1
`

func (q *Queries) DeleteEmployee(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, deleteEmployee, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteEmployeePositionsByPositionIDNotIn = `-- name: DeleteEmployeePositionsByPositionIDNotIn :exec
DELETE FROM employee_positions
WHERE position_id = $1
  AND employee_id != ALL($2::bigint[])
`

type DeleteEmployeePositionsByPositionIDNotInParams struct {
	PositionID  int64   `json:"position_id"`
	EmployeeIds []int64 `json:"employee_ids"`
}

// Position-first half of the "replace this position's employee set to match
// employee_ids exactly" diff (paired with InsertPositionEmployees, see
// ADR-0011) — deletes whatever's currently assigned but no longer
// submitted. Same "!= ALL(...) over empty is vacuously true" behavior as
// DeleteEmployeePositionsNotIn: submitting [] clears the position's entire
// employee set rather than being a no-op.
func (q *Queries) DeleteEmployeePositionsByPositionIDNotIn(ctx context.Context, arg DeleteEmployeePositionsByPositionIDNotInParams) error {
	_, err := q.db.Exec(ctx, deleteEmployeePositionsByPositionIDNotIn, arg.PositionID, arg.EmployeeIds)
	return err
}

const deleteEmployeePositionsNotIn = `-- name: DeleteEmployeePositionsNotIn :exec
DELETE FROM employee_positions
WHERE employee_id = $1
  AND position_id != ALL($2::bigint[])
`

type DeleteEmployeePositionsNotInParams struct {
	EmployeeID  int64   `json:"employee_id"`
	PositionIds []int64 `json:"position_ids"`
}

// Half of the "replace this employee's position set to match position_ids
// exactly" diff (paired with InsertEmployeePositions) — deletes whatever's
// currently assigned but no longer submitted. "!= ALL(...)" over an empty
// position_ids array is vacuously true for every row, so submitting []
// correctly clears the employee's entire position set rather than being a
// no-op (see ADR-0008).
func (q *Queries) DeleteEmployeePositionsNotIn(ctx context.Context, arg DeleteEmployeePositionsNotInParams) error {
	_, err := q.db.Exec(ctx, deleteEmployeePositionsNotIn, arg.EmployeeID, arg.PositionIds)
	return err
}

const deleteEmployeeStoresNotIn = `-- name: DeleteEmployeeStoresNotIn :exec
DELETE FROM employee_stores
WHERE employee_id = $1
  AND store_id != ALL($2::bigint[])
`

type DeleteEmployeeStoresNotInParams struct {
	EmployeeID int64   `json:"employee_id"`
	StoreIds   []int64 `json:"store_ids"`
}

// Half of the "replace this employee's store membership to match store_ids
// exactly" diff (paired with InsertEmployeeStores) — deletes whatever's
// currently assigned but no longer present in Odoo's resolved set. Unlike
// employee_positions' diff pair, only runSync ever calls this — store
// membership is Odoo-owned, never admin-writable (see ADR-0009).
func (q *Queries) DeleteEmployeeStoresNotIn(ctx context.Context, arg DeleteEmployeeStoresNotInParams) error {
	_, err := q.db.Exec(ctx, deleteEmployeeStoresNotIn, arg.EmployeeID, arg.StoreIds)
	return err
}

const deletePosition = `-- name: DeletePosition :execrows
DELETE FROM positions
WHERE id = $1
`

func (q *Queries) DeletePosition(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, deletePosition, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deletePositions = `-- name: DeletePositions :execrows
DELETE FROM positions
WHERE id = ANY($1::bigint[])
`

// Bulk-delete counterpart of DeletePosition (see issue #13) — deletes every
// submitted id in one statement. BulkDeletePositions pre-checks all ids
// exist via CountPositionsByIDs inside the same transaction, so this is
// only the "delete" half of an all-or-nothing count-check-then-delete, not
// an existence check itself.
func (q *Queries) DeletePositions(ctx context.Context, ids []int64) (int64, error) {
	result, err := q.db.Exec(ctx, deletePositions, ids)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteSessionByEmployeeID = `-- name: DeleteSessionByEmployeeID :execrows
DELETE FROM sessions
WHERE employee_id = $1
`

// CompleteActivation (issue #38): signs out any device holding a Session
// under the Employee's old password once they've completed an
// activation/reset. employee_id is UNIQUE on sessions, so this ends at most
// one row; an Employee with no open Session returns 0 rows rather than an
// error.
func (q *Queries) DeleteSessionByEmployeeID(ctx context.Context, employeeID int64) (int64, error) {
	result, err := q.db.Exec(ctx, deleteSessionByEmployeeID, employeeID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteSessionByTokenHash = `-- name: DeleteSessionByTokenHash :execrows
DELETE FROM sessions
WHERE token_hash = $1
`

// Logout: ends the Session matching this bearer token's hash immediately,
// no re-authentication required. A hash matching no row (already logged
// out, expired and reaped, or never valid) still returns 0 rows rather than
// an error — Logout is idempotent, see auth.Service.Logout. Also reused by
// Heartbeat (issue #23) to end a Session on expiry/silence/left_premises.
func (q *Queries) DeleteSessionByTokenHash(ctx context.Context, tokenHash string) (int64, error) {
	result, err := q.db.Exec(ctx, deleteSessionByTokenHash, tokenHash)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteStoreWifiIPsByValue = `-- name: DeleteStoreWifiIPsByValue :many
DELETE FROM store_wifi_ip
WHERE store_id = $1
  AND ip_address = ANY($2::inet[])
RETURNING ip_address
`

type DeleteStoreWifiIPsByValueParams struct {
	StoreID     int64        `json:"store_id"`
	IpAddresses []netip.Addr `json:"ip_addresses"`
}

// Deletes specific store_wifi_ip rows by value, not the table's internal id
// (see ADR-0003 — a value unambiguously identifies the row within a store
// thanks to the UNIQUE (store_id, ip_address) constraint) — the surgical
// per-entry removal path for DELETE /v1/stores/{id}/wifi-whitelist, as
// opposed to DeleteStoreWifiIPsNotIn's whole-list replace. RETURNING the
// deleted values (rather than a row count) lets the caller report each
// submitted value's success/failure independently and best-effort: a
// submitted value not present in the whitelist simply doesn't come back in
// this set, without erroring or blocking the rest of the batch.
func (q *Queries) DeleteStoreWifiIPsByValue(ctx context.Context, arg DeleteStoreWifiIPsByValueParams) ([]netip.Addr, error) {
	rows, err := q.db.Query(ctx, deleteStoreWifiIPsByValue, arg.StoreID, arg.IpAddresses)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []netip.Addr
	for rows.Next() {
		var ip_address netip.Addr
		if err := rows.Scan(&ip_address); err != nil {
			return nil, err
		}
		items = append(items, ip_address)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteStoreWifiIPsNotIn = `-- name: DeleteStoreWifiIPsNotIn :exec
DELETE FROM store_wifi_ip
WHERE store_id = $1
  AND ip_address != ALL($2::inet[])
`

type DeleteStoreWifiIPsNotInParams struct {
	StoreID     int64        `json:"store_id"`
	IpAddresses []netip.Addr `json:"ip_addresses"`
}

// Half of the "replace this store's IP whitelist to match ip_addresses
// exactly" diff (paired with InsertStoreWifiIPs) — deletes whatever's
// currently there but no longer submitted. "!= ALL(...)" over an empty
// ip_addresses array is vacuously true for every row, so submitting []
// correctly clears the whole whitelist rather than being a no-op.
func (q *Queries) DeleteStoreWifiIPsNotIn(ctx context.Context, arg DeleteStoreWifiIPsNotInParams) error {
	_, err := q.db.Exec(ctx, deleteStoreWifiIPsNotIn, arg.StoreID, arg.IpAddresses)
	return err
}

const deleteStoreWifiMacsByValue = `-- name: DeleteStoreWifiMacsByValue :many
DELETE FROM store_wifi_mac
WHERE store_id = $1
  AND mac_address = ANY($2::macaddr[])
RETURNING mac_address
`

type DeleteStoreWifiMacsByValueParams struct {
	StoreID      int64              `json:"store_id"`
	MacAddresses []net.HardwareAddr `json:"mac_addresses"`
}

// MAC-address counterpart of DeleteStoreWifiIPsByValue.
func (q *Queries) DeleteStoreWifiMacsByValue(ctx context.Context, arg DeleteStoreWifiMacsByValueParams) ([]net.HardwareAddr, error) {
	rows, err := q.db.Query(ctx, deleteStoreWifiMacsByValue, arg.StoreID, arg.MacAddresses)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []net.HardwareAddr
	for rows.Next() {
		var mac_address net.HardwareAddr
		if err := rows.Scan(&mac_address); err != nil {
			return nil, err
		}
		items = append(items, mac_address)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteStoreWifiMacsNotIn = `-- name: DeleteStoreWifiMacsNotIn :exec
DELETE FROM store_wifi_mac
WHERE store_id = $1
  AND mac_address != ALL($2::macaddr[])
`

type DeleteStoreWifiMacsNotInParams struct {
	StoreID      int64              `json:"store_id"`
	MacAddresses []net.HardwareAddr `json:"mac_addresses"`
}

// MAC-address counterpart of DeleteStoreWifiIPsNotIn.
func (q *Queries) DeleteStoreWifiMacsNotIn(ctx context.Context, arg DeleteStoreWifiMacsNotInParams) error {
	_, err := q.db.Exec(ctx, deleteStoreWifiMacsNotIn, arg.StoreID, arg.MacAddresses)
	return err
}

const deleteStores = `-- name: DeleteStores :execrows
DELETE FROM store
WHERE id = ANY($1::bigint[])
`

// Hard-deletes stores Odoo no longer reports (see ADR-0005) — replaces the
// former SoftDeleteStores. store_wifi_ip/store_wifi_mac cascade
// automatically (ON DELETE CASCADE, migration 00006).
func (q *Queries) DeleteStores(ctx context.Context, storeIds []int64) (int64, error) {
	result, err := q.db.Exec(ctx, deleteStores, storeIds)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const findStoresNotInOdoo = `-- name: FindStoresNotInOdoo :many
SELECT id FROM store
WHERE odoo_store_id IS NOT NULL
  AND odoo_store_id != ALL($1::varchar[])
`

// Locally-created stores that have never been linked to Odoo
// (odoo_store_id IS NULL) are deliberately excluded — only stores Odoo
// once reported and has since stopped reporting count as deleted. No
// wifi_whitelist_enabled filter (see ADR-0005) — that flag is unrelated to a
// store's existence, so filtering on it would permanently orphan a
// wifi-disabled store once it left Odoo, since it would never be selected
// here as stale.
func (q *Queries) FindStoresNotInOdoo(ctx context.Context, activeOdooStoreIds []string) ([]int64, error) {
	rows, err := q.db.Query(ctx, findStoresNotInOdoo, activeOdooStoreIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEmployeeByEmail = `-- name: GetEmployeeByEmail :one
SELECT id, odoo_employee_id, full_name, email, username, password, is_active, created_at, updated_at, failed_login_attempts, locked_until FROM employees
WHERE email = $1
`

func (q *Queries) GetEmployeeByEmail(ctx context.Context, email string) (Employee, error) {
	row := q.db.QueryRow(ctx, getEmployeeByEmail, email)
	var i Employee
	err := row.Scan(
		&i.ID,
		&i.OdooEmployeeID,
		&i.FullName,
		&i.Email,
		&i.Username,
		&i.Password,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FailedLoginAttempts,
		&i.LockedUntil,
	)
	return i, err
}

const getEmployeeByID = `-- name: GetEmployeeByID :one
SELECT id, odoo_employee_id, full_name, email, username, password, is_active, created_at, updated_at, failed_login_attempts, locked_until FROM employees
WHERE id = $1
`

func (q *Queries) GetEmployeeByID(ctx context.Context, id int64) (Employee, error) {
	row := q.db.QueryRow(ctx, getEmployeeByID, id)
	var i Employee
	err := row.Scan(
		&i.ID,
		&i.OdooEmployeeID,
		&i.FullName,
		&i.Email,
		&i.Username,
		&i.Password,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FailedLoginAttempts,
		&i.LockedUntil,
	)
	return i, err
}

const getEmployeeByUsername = `-- name: GetEmployeeByUsername :one
SELECT id, odoo_employee_id, full_name, email, username, password, is_active, created_at, updated_at, failed_login_attempts, locked_until FROM employees
WHERE username = $1
`

func (q *Queries) GetEmployeeByUsername(ctx context.Context, username string) (Employee, error) {
	row := q.db.QueryRow(ctx, getEmployeeByUsername, username)
	var i Employee
	err := row.Scan(
		&i.ID,
		&i.OdooEmployeeID,
		&i.FullName,
		&i.Email,
		&i.Username,
		&i.Password,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FailedLoginAttempts,
		&i.LockedUntil,
	)
	return i, err
}

const getPositionByID = `-- name: GetPositionByID :one
SELECT id, name, created_at, updated_at FROM positions
WHERE id = $1
`

// Existence check for the position-first endpoints (ADR-0011) — GET/PUT
// /positions/{id}/employees both need to 404 on an unknown position id
// before touching employee_positions.
func (q *Queries) GetPositionByID(ctx context.Context, id int64) (Position, error) {
	row := q.db.QueryRow(ctx, getPositionByID, id)
	var i Position
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSessionByTokenHash = `-- name: GetSessionByTokenHash :one
SELECT id, employee_id, store_id, token_hash, issued_at, expires_at, last_heartbeat_at, consecutive_failures FROM sessions
WHERE token_hash = $1
`

// Heartbeat's (issue #23) and ValidateSession's (issue #25) lookup of the
// Session a bearer token currently names. A hash matching no row — never
// valid, already logged out/expired-and-ended, or (for a stale token still
// held by a device) superseded by a newer Login's UpsertSession overwriting
// the same employee_id row in place — is pgx.ErrNoRows; the caller can't
// distinguish those cases from this query alone, which is why Heartbeat
// reports the generic logged_out_elsewhere reason for all of them (see
// auth.Service.Heartbeat).
func (q *Queries) GetSessionByTokenHash(ctx context.Context, tokenHash string) (Session, error) {
	row := q.db.QueryRow(ctx, getSessionByTokenHash, tokenHash)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.EmployeeID,
		&i.StoreID,
		&i.TokenHash,
		&i.IssuedAt,
		&i.ExpiresAt,
		&i.LastHeartbeatAt,
		&i.ConsecutiveFailures,
	)
	return i, err
}

const getStoreByID = `-- name: GetStoreByID :one
SELECT id, odoo_store_id, store_name, city, latitude, longitude, radius_meters, wifi_whitelist_enabled, created_at, updated_at FROM store
WHERE id = $1
`

// No wifi_whitelist_enabled filter — see ADR-0001/ADR-0004, it's a normal
// editable field, not a soft-delete tombstone, so a wifi-disabled store is
// still a normal fetch here, not a 404.
func (q *Queries) GetStoreByID(ctx context.Context, id int64) (Store, error) {
	row := q.db.QueryRow(ctx, getStoreByID, id)
	var i Store
	err := row.Scan(
		&i.ID,
		&i.OdooStoreID,
		&i.StoreName,
		&i.City,
		&i.Latitude,
		&i.Longitude,
		&i.RadiusMeters,
		&i.WifiWhitelistEnabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getStoresByIDsForUpdate = `-- name: GetStoresByIDsForUpdate :many
SELECT id, updated_at FROM store
WHERE id = ANY($1::bigint[])
FOR UPDATE
`

type GetStoresByIDsForUpdateRow struct {
	ID        int64              `json:"id"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

// Pre-check pass for bulk PATCH /v1/stores (see ADR-0006): fetches every
// submitted id's current (id, updated_at) inside the same transaction as the
// bulk UPDATE that follows, so the service can compare against the caller's
// submitted pairs before writing anything — any missing id or stale
// updated_at aborts the whole request. FOR UPDATE locks these rows so a
// concurrent mutation can't slip in between this check and the bulk UPDATE.
func (q *Queries) GetStoresByIDsForUpdate(ctx context.Context, storeIds []int64) ([]GetStoresByIDsForUpdateRow, error) {
	rows, err := q.db.Query(ctx, getStoresByIDsForUpdate, storeIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetStoresByIDsForUpdateRow
	for rows.Next() {
		var i GetStoresByIDsForUpdateRow
		if err := rows.Scan(&i.ID, &i.UpdatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertEmployeePositions = `-- name: InsertEmployeePositions :exec
INSERT INTO employee_positions (employee_id, position_id)
SELECT $1, unnest($2::bigint[])
ON CONFLICT (employee_id, position_id) DO NOTHING
`

type InsertEmployeePositionsParams struct {
	EmployeeID  int64   `json:"employee_id"`
	PositionIds []int64 `json:"position_ids"`
}

// Other half of the replace diff: inserts whatever's newly submitted.
// ON CONFLICT DO NOTHING is what makes assignments already present in both
// the old and new set stay untouched rather than being deleted and
// reinserted.
func (q *Queries) InsertEmployeePositions(ctx context.Context, arg InsertEmployeePositionsParams) error {
	_, err := q.db.Exec(ctx, insertEmployeePositions, arg.EmployeeID, arg.PositionIds)
	return err
}

const insertEmployeeStores = `-- name: InsertEmployeeStores :exec
INSERT INTO employee_stores (employee_id, store_id)
SELECT $1, unnest($2::bigint[])
ON CONFLICT (employee_id, store_id) DO NOTHING
`

type InsertEmployeeStoresParams struct {
	EmployeeID int64   `json:"employee_id"`
	StoreIds   []int64 `json:"store_ids"`
}

// Other half of the replace diff: inserts whatever's newly resolved.
// ON CONFLICT DO NOTHING is what makes assignments already present in both
// the old and new set stay untouched rather than being deleted and
// reinserted.
func (q *Queries) InsertEmployeeStores(ctx context.Context, arg InsertEmployeeStoresParams) error {
	_, err := q.db.Exec(ctx, insertEmployeeStores, arg.EmployeeID, arg.StoreIds)
	return err
}

const insertPositionEmployees = `-- name: InsertPositionEmployees :exec
INSERT INTO employee_positions (employee_id, position_id)
SELECT unnest($1::bigint[]), $2
ON CONFLICT (employee_id, position_id) DO NOTHING
`

type InsertPositionEmployeesParams struct {
	EmployeeIds []int64 `json:"employee_ids"`
	PositionID  int64   `json:"position_id"`
}

// Position-first half of the replace diff: inserts whatever's newly
// submitted. ON CONFLICT DO NOTHING is what makes assignments already
// present in both the old and new set stay untouched rather than being
// deleted and reinserted.
func (q *Queries) InsertPositionEmployees(ctx context.Context, arg InsertPositionEmployeesParams) error {
	_, err := q.db.Exec(ctx, insertPositionEmployees, arg.EmployeeIds, arg.PositionID)
	return err
}

const insertStoreWifiIPs = `-- name: InsertStoreWifiIPs :exec
INSERT INTO store_wifi_ip (store_id, ip_address)
SELECT $1, unnest($2::inet[])
ON CONFLICT (store_id, ip_address) DO NOTHING
`

type InsertStoreWifiIPsParams struct {
	StoreID     int64        `json:"store_id"`
	IpAddresses []netip.Addr `json:"ip_addresses"`
}

// Other half of the replace diff: inserts whatever's newly submitted.
// ON CONFLICT DO NOTHING is what makes values already present in both the
// old and new set stay untouched rather than being deleted and reinserted.
func (q *Queries) InsertStoreWifiIPs(ctx context.Context, arg InsertStoreWifiIPsParams) error {
	_, err := q.db.Exec(ctx, insertStoreWifiIPs, arg.StoreID, arg.IpAddresses)
	return err
}

const insertStoreWifiMacs = `-- name: InsertStoreWifiMacs :exec
INSERT INTO store_wifi_mac (store_id, mac_address)
SELECT $1, unnest($2::macaddr[])
ON CONFLICT (store_id, mac_address) DO NOTHING
`

type InsertStoreWifiMacsParams struct {
	StoreID      int64              `json:"store_id"`
	MacAddresses []net.HardwareAddr `json:"mac_addresses"`
}

// MAC-address counterpart of InsertStoreWifiIPs.
func (q *Queries) InsertStoreWifiMacs(ctx context.Context, arg InsertStoreWifiMacsParams) error {
	_, err := q.db.Exec(ctx, insertStoreWifiMacs, arg.StoreID, arg.MacAddresses)
	return err
}

const invalidatePasswordResetTokensByEmployeeID = `-- name: InvalidatePasswordResetTokensByEmployeeID :exec
UPDATE password_reset_tokens
SET used_at = now()
WHERE employee_id = $1
  AND used_at IS NULL
`

// Marks every still-outstanding (unused) token for an Employee as consumed.
// Called by issuePasswordResetToken before it inserts a new token, so at
// most one issued token is ever redeemable per Employee at a time.
func (q *Queries) InvalidatePasswordResetTokensByEmployeeID(ctx context.Context, employeeID int64) error {
	_, err := q.db.Exec(ctx, invalidatePasswordResetTokensByEmployeeID, employeeID)
	return err
}

const isEmployeeAdmin = `-- name: IsEmployeeAdmin :one
SELECT EXISTS (
    SELECT 1
    FROM employee_positions ep
    JOIN positions p ON p.id = ep.position_id
    WHERE ep.employee_id = $1
    AND LOWER(p.name) = 'admin'
)
`

// The single centralized "does this Employee hold the Admin Position" check
// ADR-0015 calls for — an exact, case-insensitive match on the Position
// name "Admin", not a pattern. Shared by Login's presence-check bypass
// (issue #24) and the admin-gating middleware (issue #25); no other call
// site should reimplement this comparison.
func (q *Queries) IsEmployeeAdmin(ctx context.Context, employeeID int64) (bool, error) {
	row := q.db.QueryRow(ctx, isEmployeeAdmin, employeeID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listEmployeeIDsByIDs = `-- name: ListEmployeeIDsByIDs :many
SELECT odoo_employee_id FROM employees
WHERE id = ANY($1::bigint[])
`

// Translates the internal ids a SyncEmployees caller supplies into the
// Odoo-facing odoo_employee_id values runSync actually sends to Odoo. An id
// with no matching row is silently omitted from the result.
func (q *Queries) ListEmployeeIDsByIDs(ctx context.Context, ids []int64) ([]int64, error) {
	rows, err := q.db.Query(ctx, listEmployeeIDsByIDs, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var odoo_employee_id int64
		if err := rows.Scan(&odoo_employee_id); err != nil {
			return nil, err
		}
		items = append(items, odoo_employee_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEmployees = `-- name: ListEmployees :many
SELECT id, odoo_employee_id, full_name, email, username, password, is_active, created_at, updated_at, failed_login_attempts, locked_until FROM employees
WHERE ($1::text IS NULL OR full_name ILIKE '%' || replace(replace(replace($1::text, '\', '\\'), '%', '\%'), '_', '\_') || '%' OR email ILIKE '%' || replace(replace(replace($1::text, '\', '\\'), '%', '\%'), '_', '\_') || '%')
  AND ($2::bigint[] IS NULL OR id IN (SELECT employee_id FROM employee_positions WHERE position_id = ANY($2::bigint[])))
  AND ($3::bigint[] IS NULL OR id IN (SELECT employee_id FROM employee_stores WHERE store_id = ANY($3::bigint[])))
  AND ($4::bigint[] IS NULL OR odoo_employee_id = ANY($4::bigint[]))
  AND ($5::bool IS NULL OR is_active = $5::bool)
ORDER BY lower(full_name) ASC
`

type ListEmployeesParams struct {
	Q               pgtype.Text `json:"q"`
	PositionIds     []int64     `json:"position_ids"`
	StoreIds        []int64     `json:"store_ids"`
	OdooEmployeeIds []int64     `json:"odoo_employee_ids"`
	IsActive        pgtype.Bool `json:"is_active"`
}

// Optional-filter search for issue #28: every sqlc.narg(...) IS NULL check
// skips that facet entirely when the caller omitted the corresponding query
// parameter (employees.ListEmployeesFilter's zero value) — the standard
// "$n IS NULL means skip this filter" static-SQL pattern (sqlc requires
// compile-time SQL, so filters can't be built by string concatenation).
// position_ids and store_ids are independent, OR-within/AND-across facets —
// never paired (ADR-0008, ADR-0009; issue #28 user story 7) — and each is
// matched via a sub-SELECT against its join table rather than a JOIN, so an
// employee with zero positions/stores still matches when that facet's
// filter is omitted (user stories 8-9). Sorted case-insensitively by
// full_name (user story 10) since Postgres' default collation is
// case-sensitive.
func (q *Queries) ListEmployees(ctx context.Context, arg ListEmployeesParams) ([]Employee, error) {
	rows, err := q.db.Query(ctx, listEmployees,
		arg.Q,
		arg.PositionIds,
		arg.StoreIds,
		arg.OdooEmployeeIds,
		arg.IsActive,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Employee
	for rows.Next() {
		var i Employee
		if err := rows.Scan(
			&i.ID,
			&i.OdooEmployeeID,
			&i.FullName,
			&i.Email,
			&i.Username,
			&i.Password,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.FailedLoginAttempts,
			&i.LockedUntil,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEmployeesByPositionID = `-- name: ListEmployeesByPositionID :many
SELECT e.id, e.odoo_employee_id, e.full_name, e.email, e.username, e.password, e.is_active, e.created_at, e.updated_at, e.failed_login_attempts, e.locked_until FROM employees e
JOIN employee_positions ep ON ep.employee_id = e.id
WHERE ep.position_id = $1
ORDER BY e.id
`

// Position-first counterpart of ListPositionIDsByEmployeeID, for
// GET/PUT /positions/{id}/employees — returns full employee rows (not just
// ids) so the position package can build the same employeeResponse shape
// GET /employees already returns (see issue #13).
func (q *Queries) ListEmployeesByPositionID(ctx context.Context, positionID int64) ([]Employee, error) {
	rows, err := q.db.Query(ctx, listEmployeesByPositionID, positionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Employee
	for rows.Next() {
		var i Employee
		if err := rows.Scan(
			&i.ID,
			&i.OdooEmployeeID,
			&i.FullName,
			&i.Email,
			&i.Username,
			&i.Password,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.FailedLoginAttempts,
			&i.LockedUntil,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPositionIDsByEmployeeID = `-- name: ListPositionIDsByEmployeeID :many
SELECT position_id FROM employee_positions
WHERE employee_id = $1
ORDER BY position_id
`

func (q *Queries) ListPositionIDsByEmployeeID(ctx context.Context, employeeID int64) ([]int64, error) {
	rows, err := q.db.Query(ctx, listPositionIDsByEmployeeID, employeeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var position_id int64
		if err := rows.Scan(&position_id); err != nil {
			return nil, err
		}
		items = append(items, position_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPositionIDsByEmployeeIDs = `-- name: ListPositionIDsByEmployeeIDs :many
SELECT employee_id, position_id FROM employee_positions
WHERE employee_id = ANY($1::bigint[])
ORDER BY employee_id, position_id
`

// Bulk counterpart of ListPositionIDsByEmployeeID for ListEmployees — one
// round trip for every employee's position ids, grouped client-side by
// employee_id rather than aggregated here (keeps this query a plain
// row-per-pair scan, same shape as the single-employee version).
func (q *Queries) ListPositionIDsByEmployeeIDs(ctx context.Context, employeeIds []int64) ([]EmployeePosition, error) {
	rows, err := q.db.Query(ctx, listPositionIDsByEmployeeIDs, employeeIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EmployeePosition
	for rows.Next() {
		var i EmployeePosition
		if err := rows.Scan(&i.EmployeeID, &i.PositionID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPositions = `-- name: ListPositions :many
SELECT id, name, created_at, updated_at FROM positions
ORDER BY name
`

func (q *Queries) ListPositions(ctx context.Context) ([]Position, error) {
	rows, err := q.db.Query(ctx, listPositions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Position
	for rows.Next() {
		var i Position
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStoreIDsByEmployeeID = `-- name: ListStoreIDsByEmployeeID :many
SELECT store_id FROM employee_stores
WHERE employee_id = $1
ORDER BY store_id
`

func (q *Queries) ListStoreIDsByEmployeeID(ctx context.Context, employeeID int64) ([]int64, error) {
	rows, err := q.db.Query(ctx, listStoreIDsByEmployeeID, employeeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var store_id int64
		if err := rows.Scan(&store_id); err != nil {
			return nil, err
		}
		items = append(items, store_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStoreIDsByEmployeeIDs = `-- name: ListStoreIDsByEmployeeIDs :many
SELECT employee_id, store_id FROM employee_stores
WHERE employee_id = ANY($1::bigint[])
ORDER BY employee_id, store_id
`

// Bulk counterpart of ListStoreIDsByEmployeeID for ListEmployees — same
// plain row-per-pair shape as ListPositionIDsByEmployeeIDs, grouped
// client-side by employee_id.
func (q *Queries) ListStoreIDsByEmployeeIDs(ctx context.Context, employeeIds []int64) ([]EmployeeStore, error) {
	rows, err := q.db.Query(ctx, listStoreIDsByEmployeeIDs, employeeIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EmployeeStore
	for rows.Next() {
		var i EmployeeStore
		if err := rows.Scan(&i.EmployeeID, &i.StoreID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStoreWifiIPsByStoreID = `-- name: ListStoreWifiIPsByStoreID :many
SELECT ip_address FROM store_wifi_ip
WHERE store_id = $1
ORDER BY id
`

func (q *Queries) ListStoreWifiIPsByStoreID(ctx context.Context, storeID int64) ([]netip.Addr, error) {
	rows, err := q.db.Query(ctx, listStoreWifiIPsByStoreID, storeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []netip.Addr
	for rows.Next() {
		var ip_address netip.Addr
		if err := rows.Scan(&ip_address); err != nil {
			return nil, err
		}
		items = append(items, ip_address)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStoreWifiMacsByStoreID = `-- name: ListStoreWifiMacsByStoreID :many
SELECT mac_address FROM store_wifi_mac
WHERE store_id = $1
ORDER BY id
`

func (q *Queries) ListStoreWifiMacsByStoreID(ctx context.Context, storeID int64) ([]net.HardwareAddr, error) {
	rows, err := q.db.Query(ctx, listStoreWifiMacsByStoreID, storeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []net.HardwareAddr
	for rows.Next() {
		var mac_address net.HardwareAddr
		if err := rows.Scan(&mac_address); err != nil {
			return nil, err
		}
		items = append(items, mac_address)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStores = `-- name: ListStores :many
SELECT
    s.id, s.odoo_store_id, s.store_name, s.city, s.latitude, s.longitude, s.radius_meters, s.wifi_whitelist_enabled, s.created_at, s.updated_at,
    COALESCE(ip.ip_addresses, '{}')::inet[] AS ip_addresses,
    COALESCE(mac.mac_addresses, '{}')::macaddr[] AS mac_addresses
FROM store s
LEFT JOIN LATERAL (
    SELECT array_agg(ip_address ORDER BY id) AS ip_addresses
    FROM store_wifi_ip
    WHERE store_id = s.id
) ip ON true
LEFT JOIN LATERAL (
    SELECT array_agg(mac_address ORDER BY id) AS mac_addresses
    FROM store_wifi_mac
    WHERE store_id = s.id
) mac ON true
WHERE ($1::text IS NULL OR s.store_name ILIKE '%' || replace(replace(replace($1::text, '\', '\\'), '%', '\%'), '_', '\_') || '%')
  AND ($2::text IS NULL OR s.city ILIKE '%' || replace(replace(replace($2::text, '\', '\\'), '%', '\%'), '_', '\_') || '%')
  AND ($3::bool IS NULL OR s.wifi_whitelist_enabled = $3::bool)
  AND ($4::varchar[] IS NULL OR s.odoo_store_id = ANY($4::varchar[]))
ORDER BY lower(s.store_name) ASC
`

type ListStoresParams struct {
	StoreName            pgtype.Text `json:"store_name"`
	City                 pgtype.Text `json:"city"`
	WifiWhitelistEnabled pgtype.Bool `json:"wifi_whitelist_enabled"`
	OdooStoreIds         []string    `json:"odoo_store_ids"`
}

type ListStoresRow struct {
	Store        Store              `json:"store"`
	IpAddresses  []netip.Addr       `json:"ip_addresses"`
	MacAddresses []net.HardwareAddr `json:"mac_addresses"`
}

// Every store (wifi-enabled and wifi-disabled — the list screen's Activate
// toggle needs to see and re-enable wifi-disabled stores), each with its
// current IP/MAC whitelist aggregated in the same round trip rather than one
// query per store. LATERAL subqueries (rather than a single LEFT JOIN +
// array_agg) keep the two independent whitelists from cross-joining each
// other.
//
// Optional-filter search for issues #32/#33/#34: every sqlc.narg(...) IS
// NULL check skips that facet entirely when the caller omitted the
// corresponding query parameter (stores.ListStoresFilter's zero value), same
// "$n IS NULL means skip this filter" pattern as ListEmployees (issue #28).
// store_name and city are independent, AND-across facets, each a
// case-insensitive substring match; city never matches a store with no city
// set, since NULL city ILIKE anything is NULL (falsy), not true.
// wifi_whitelist_enabled (issue #33) is an exact-match boolean facet, AND'd
// with the rest. odoo_store_ids (issue #34) is OR-within/AND-across, same
// shape as ListStoresByOdooStoreIDs' odoo_store_id = ANY(...) — matched
// against s.odoo_store_id, VARCHAR not bigint (unlike ListEmployees'
// odoo_employee_ids), so a NULL odoo_store_id never matches, same as city.
// Sorted case-insensitively by store_name (issue #32), replacing the former
// ORDER BY s.city, s.store_name.
func (q *Queries) ListStores(ctx context.Context, arg ListStoresParams) ([]ListStoresRow, error) {
	rows, err := q.db.Query(ctx, listStores,
		arg.StoreName,
		arg.City,
		arg.WifiWhitelistEnabled,
		arg.OdooStoreIds,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListStoresRow
	for rows.Next() {
		var i ListStoresRow
		if err := rows.Scan(
			&i.Store.ID,
			&i.Store.OdooStoreID,
			&i.Store.StoreName,
			&i.Store.City,
			&i.Store.Latitude,
			&i.Store.Longitude,
			&i.Store.RadiusMeters,
			&i.Store.WifiWhitelistEnabled,
			&i.Store.CreatedAt,
			&i.Store.UpdatedAt,
			&i.IpAddresses,
			&i.MacAddresses,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStoresByOdooStoreIDs = `-- name: ListStoresByOdooStoreIDs :many
SELECT id, odoo_store_id FROM store
WHERE odoo_store_id = ANY($1::varchar[])
`

type ListStoresByOdooStoreIDsRow struct {
	ID          int64       `json:"id"`
	OdooStoreID pgtype.Text `json:"odoo_store_id"`
}

// Resolves a batch of Odoo store ids (matched against store's VARCHAR
// odoo_store_id join key — the same one SyncStores already uses) to this
// system's internal store.id, for employee sync to map each employee's
// Odoo store membership onto local store rows (see ADR-0009). An
// odoo_store_id with no matching row is simply absent from the result; the
// caller (runSync) logs and skips those rather than failing the sync.
func (q *Queries) ListStoresByOdooStoreIDs(ctx context.Context, odooStoreIds []string) ([]ListStoresByOdooStoreIDsRow, error) {
	rows, err := q.db.Query(ctx, listStoresByOdooStoreIDs, odooStoreIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListStoresByOdooStoreIDsRow
	for rows.Next() {
		var i ListStoresByOdooStoreIDsRow
		if err := rows.Scan(&i.ID, &i.OdooStoreID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStoresForLoginByEmployeeID = `-- name: ListStoresForLoginByEmployeeID :many
SELECT
    s.id, s.odoo_store_id, s.store_name, s.city, s.latitude, s.longitude, s.radius_meters, s.wifi_whitelist_enabled, s.created_at, s.updated_at,
    COALESCE(ip.ip_addresses, '{}')::inet[] AS ip_addresses,
    COALESCE(mac.mac_addresses, '{}')::macaddr[] AS mac_addresses
FROM store s
JOIN employee_stores es ON es.store_id = s.id
LEFT JOIN LATERAL (
    SELECT array_agg(ip_address ORDER BY id) AS ip_addresses
    FROM store_wifi_ip
    WHERE store_id = s.id
) ip ON true
LEFT JOIN LATERAL (
    SELECT array_agg(mac_address ORDER BY id) AS mac_addresses
    FROM store_wifi_mac
    WHERE store_id = s.id
) mac ON true
WHERE es.employee_id = $1
ORDER BY s.id
`

type ListStoresForLoginByEmployeeIDRow struct {
	Store        Store              `json:"store"`
	IpAddresses  []netip.Addr       `json:"ip_addresses"`
	MacAddresses []net.HardwareAddr `json:"mac_addresses"`
}

// Every Store an Employee belongs to, each with its current IP and MAC
// whitelists — Login's (issues #21/#22) candidate set for the IP/Geofence/MAC
// presence check (ADR-0013). Ordered by store id, the deterministic
// tie-break auth.matchStore relies on when more than one Store could
// plausibly match. wifi_whitelist_enabled comes along on the embedded
// Store row so the caller can gate the IP/MAC tiers per store without a
// second query; geofence columns are on the same row for the same reason.
func (q *Queries) ListStoresForLoginByEmployeeID(ctx context.Context, employeeID int64) ([]ListStoresForLoginByEmployeeIDRow, error) {
	rows, err := q.db.Query(ctx, listStoresForLoginByEmployeeID, employeeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListStoresForLoginByEmployeeIDRow
	for rows.Next() {
		var i ListStoresForLoginByEmployeeIDRow
		if err := rows.Scan(
			&i.Store.ID,
			&i.Store.OdooStoreID,
			&i.Store.StoreName,
			&i.Store.City,
			&i.Store.Latitude,
			&i.Store.Longitude,
			&i.Store.RadiusMeters,
			&i.Store.WifiWhitelistEnabled,
			&i.Store.CreatedAt,
			&i.Store.UpdatedAt,
			&i.IpAddresses,
			&i.MacAddresses,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordFailedLoginAttempt = `-- name: RecordFailedLoginAttempt :one
UPDATE employees e
SET failed_login_attempts = calc.new_count,
    locked_until = CASE
        WHEN calc.new_count >= $1::int THEN $2::timestamptz
        ELSE NULL
    END
FROM (
    SELECT emp.id,
        CASE
            WHEN emp.locked_until IS NOT NULL AND emp.locked_until <= now() THEN 1
            ELSE emp.failed_login_attempts + 1
        END AS new_count
    FROM employees emp
    WHERE emp.id = $3
) AS calc
WHERE e.id = calc.id
RETURNING e.id, e.odoo_employee_id, e.full_name, e.email, e.username, e.password, e.is_active, e.created_at, e.updated_at, e.failed_login_attempts, e.locked_until
`

type RecordFailedLoginAttemptParams struct {
	Threshold   int32              `json:"threshold"`
	LockedUntil pgtype.Timestamptz `json:"locked_until"`
	ID          int64              `json:"id"`
}

// Atomically increments failed_login_attempts and, only once the new count
// reaches sqlc.arg(threshold), sets locked_until to sqlc.arg(locked_until)
// (computed in Go as now + the lockout duration, so the duration itself
// stays a Go constant, not a SQL literal — see auth.loginLockoutDuration).
// Callers (auth.Service.Login) only ever reach this query once they've
// already confirmed locked_until is unset or in the past — an
// Employee still inside an active lockout window never gets here. Given
// that, "consecutive" resets the moment a prior lockout has fully elapsed:
// if locked_until is already in the past, this failed attempt is attempt 1
// of a fresh run, not a continuation of the old count — otherwise a single
// failure right after a lockout expires would instantly re-lock the
// Employee instead of giving them a full new run of attempts.
func (q *Queries) RecordFailedLoginAttempt(ctx context.Context, arg RecordFailedLoginAttemptParams) (Employee, error) {
	row := q.db.QueryRow(ctx, recordFailedLoginAttempt, arg.Threshold, arg.LockedUntil, arg.ID)
	var i Employee
	err := row.Scan(
		&i.ID,
		&i.OdooEmployeeID,
		&i.FullName,
		&i.Email,
		&i.Username,
		&i.Password,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FailedLoginAttempts,
		&i.LockedUntil,
	)
	return i, err
}

const recordHeartbeatFailure = `-- name: RecordHeartbeatFailure :one
UPDATE sessions
SET last_heartbeat_at = now(),
    consecutive_failures = consecutive_failures + 1
WHERE token_hash = $1
RETURNING id, employee_id, store_id, token_hash, issued_at, expires_at, last_heartbeat_at, consecutive_failures
`

// A Heartbeat (issue #23) whose presence recheck did not match the Session's
// Store: still refreshes last_heartbeat_at (a failed check is still a check
// that arrived — only true silence should trip the 90s backstop) and
// increments consecutive_failures by one. The caller (auth.Service.Heartbeat)
// ends the Session once the returned count reaches 2.
func (q *Queries) RecordHeartbeatFailure(ctx context.Context, tokenHash string) (Session, error) {
	row := q.db.QueryRow(ctx, recordHeartbeatFailure, tokenHash)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.EmployeeID,
		&i.StoreID,
		&i.TokenHash,
		&i.IssuedAt,
		&i.ExpiresAt,
		&i.LastHeartbeatAt,
		&i.ConsecutiveFailures,
	)
	return i, err
}

const recordHeartbeatSuccess = `-- name: RecordHeartbeatSuccess :one
UPDATE sessions
SET last_heartbeat_at = now(),
    consecutive_failures = 0
WHERE token_hash = $1
RETURNING id, employee_id, store_id, token_hash, issued_at, expires_at, last_heartbeat_at, consecutive_failures
`

// A Heartbeat (issue #23) whose presence recheck matched the Session's Store:
// resets consecutive_failures to 0 (a pass between failures forgives them,
// per ADR-0014) and refreshes last_heartbeat_at so the 90s silence backstop's
// clock restarts. Does not touch expires_at — the 12-hour cap is absolute,
// not extended by a passing Heartbeat.
func (q *Queries) RecordHeartbeatSuccess(ctx context.Context, tokenHash string) (Session, error) {
	row := q.db.QueryRow(ctx, recordHeartbeatSuccess, tokenHash)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.EmployeeID,
		&i.StoreID,
		&i.TokenHash,
		&i.IssuedAt,
		&i.ExpiresAt,
		&i.LastHeartbeatAt,
		&i.ConsecutiveFailures,
	)
	return i, err
}

const redeemPasswordResetToken = `-- name: RedeemPasswordResetToken :one
UPDATE password_reset_tokens
SET used_at = now()
WHERE token_hash = $1
  AND used_at IS NULL
  AND expires_at > now()
RETURNING id, employee_id, token_hash, expires_at, used_at, created_at
`

// Atomically claims a valid, unused token: the UPDATE's row lock ensures
// only one concurrent caller can match the WHERE clause and get a row back,
// so CompleteActivation can't be raced into redeeming the same token twice.
// Callers pass the SHA-256 digest of the bearer token, not the raw value.
func (q *Queries) RedeemPasswordResetToken(ctx context.Context, tokenHash string) (PasswordResetToken, error) {
	row := q.db.QueryRow(ctx, redeemPasswordResetToken, tokenHash)
	var i PasswordResetToken
	err := row.Scan(
		&i.ID,
		&i.EmployeeID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const resetFailedLoginAttempts = `-- name: ResetFailedLoginAttempts :exec
UPDATE employees
SET failed_login_attempts = 0,
    locked_until = NULL
WHERE id = $1
`

// Clears an Employee's lockout state on a successful password check
// (Login), regardless of whether the subsequent presence check goes on to
// match a Store — a correct password is what "consecutive failed attempts"
// counts, not the presence outcome.
func (q *Queries) ResetFailedLoginAttempts(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, resetFailedLoginAttempts, id)
	return err
}

const setEmployeeActive = `-- name: SetEmployeeActive :execrows
UPDATE employees
SET is_active = $2,
    updated_at = now()
WHERE id = $1
`

type SetEmployeeActiveParams struct {
	ID       int64 `json:"id"`
	IsActive bool  `json:"is_active"`
}

func (q *Queries) SetEmployeeActive(ctx context.Context, arg SetEmployeeActiveParams) (int64, error) {
	result, err := q.db.Exec(ctx, setEmployeeActive, arg.ID, arg.IsActive)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setEmployeePassword = `-- name: SetEmployeePassword :execrows
UPDATE employees
SET password = $2,
    updated_at = now()
WHERE id = $1
`

type SetEmployeePasswordParams struct {
	ID       int64  `json:"id"`
	Password []byte `json:"password"`
}

func (q *Queries) SetEmployeePassword(ctx context.Context, arg SetEmployeePasswordParams) (int64, error) {
	result, err := q.db.Exec(ctx, setEmployeePassword, arg.ID, arg.Password)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setStoreWifiWhitelistEnabled = `-- name: SetStoreWifiWhitelistEnabled :one
UPDATE store
SET wifi_whitelist_enabled = $1,
    updated_at = now()
WHERE id = $2
  AND updated_at = $3
RETURNING id, updated_at
`

type SetStoreWifiWhitelistEnabledParams struct {
	WifiWhitelistEnabled bool               `json:"wifi_whitelist_enabled"`
	ID                   int64              `json:"id"`
	ExpectedUpdatedAt    pgtype.Timestamptz `json:"expected_updated_at"`
}

type SetStoreWifiWhitelistEnabledRow struct {
	ID        int64              `json:"id"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

// PATCH /v1/stores/{id}/wifi-whitelist-enabled's single query — same
// conditional-update-returning-0-rows-on-mismatch shape as
// UpdateStoreGeofence, but scoped to just this one column since this
// endpoint only ever does one thing (see ADR-0006). No returned row
// (pgx.ErrNoRows) means either the store doesn't exist, or
// expected_updated_at is stale; the caller disambiguates with a follow-up
// GetStoreByID.
func (q *Queries) SetStoreWifiWhitelistEnabled(ctx context.Context, arg SetStoreWifiWhitelistEnabledParams) (SetStoreWifiWhitelistEnabledRow, error) {
	row := q.db.QueryRow(ctx, setStoreWifiWhitelistEnabled, arg.WifiWhitelistEnabled, arg.ID, arg.ExpectedUpdatedAt)
	var i SetStoreWifiWhitelistEnabledRow
	err := row.Scan(&i.ID, &i.UpdatedAt)
	return i, err
}

const updateEmployee = `-- name: UpdateEmployee :one
UPDATE employees
SET odoo_employee_id = $2,
    full_name = $3,
    email = $4,
    username = $5,
    updated_at = now()
WHERE id = $1
RETURNING id, odoo_employee_id, full_name, email, username, password, is_active, created_at, updated_at, failed_login_attempts, locked_until
`

type UpdateEmployeeParams struct {
	ID             int64  `json:"id"`
	OdooEmployeeID int64  `json:"odoo_employee_id"`
	FullName       string `json:"full_name"`
	Email          string `json:"email"`
	Username       string `json:"username"`
}

func (q *Queries) UpdateEmployee(ctx context.Context, arg UpdateEmployeeParams) (Employee, error) {
	row := q.db.QueryRow(ctx, updateEmployee,
		arg.ID,
		arg.OdooEmployeeID,
		arg.FullName,
		arg.Email,
		arg.Username,
	)
	var i Employee
	err := row.Scan(
		&i.ID,
		&i.OdooEmployeeID,
		&i.FullName,
		&i.Email,
		&i.Username,
		&i.Password,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FailedLoginAttempts,
		&i.LockedUntil,
	)
	return i, err
}

const updatePosition = `-- name: UpdatePosition :one
UPDATE positions
SET name = $2,
    updated_at = now()
WHERE id = $1
RETURNING id, name, created_at, updated_at
`

type UpdatePositionParams struct {
	ID   int64  `json:"id"`
	Name string `json:"name"`
}

func (q *Queries) UpdatePosition(ctx context.Context, arg UpdatePositionParams) (Position, error) {
	row := q.db.QueryRow(ctx, updatePosition, arg.ID, arg.Name)
	var i Position
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateStoreGeofence = `-- name: UpdateStoreGeofence :one
UPDATE store
SET latitude = COALESCE($1, latitude),
    longitude = COALESCE($2, longitude),
    radius_meters = COALESCE($3, radius_meters),
    updated_at = now()
WHERE id = $4
  AND updated_at = $5
RETURNING id, odoo_store_id, store_name, city, latitude, longitude, radius_meters, wifi_whitelist_enabled, created_at, updated_at
`

type UpdateStoreGeofenceParams struct {
	Latitude          pgtype.Numeric     `json:"latitude"`
	Longitude         pgtype.Numeric     `json:"longitude"`
	RadiusMeters      pgtype.Int4        `json:"radius_meters"`
	ID                int64              `json:"id"`
	ExpectedUpdatedAt pgtype.Timestamptz `json:"expected_updated_at"`
}

// Updates a store's geofence, and unconditionally bumps updated_at whenever
// expected_updated_at still matches the current row — the
// optimistic-concurrency check for the whole PATCH /v1/stores/{id} aggregate
// (store row + wifi whitelist tables), not just the geofence. A caller that
// only touches the wifi lists (ticket 03) or touches neither (ticket 06's
// delete endpoint, to bump updated_at alone) still runs this with the
// geofence narg columns NULL, still bumping updated_at.
// latitude/longitude/radius_meters are nullable args: NULL means "leave this
// column unchanged" (COALESCE keeps the existing value) rather than "clear
// it" — the all-or-nothing geofence group is enforced by the caller, not
// here. wifi_whitelist_enabled is not part of this query at all — see
// ADR-0006, it's set exclusively via its own dedicated endpoints. No
// returned row (pgx.ErrNoRows) means either the store doesn't exist, or
// expected_updated_at is stale; the caller disambiguates with a follow-up
// GetStoreByID.
func (q *Queries) UpdateStoreGeofence(ctx context.Context, arg UpdateStoreGeofenceParams) (Store, error) {
	row := q.db.QueryRow(ctx, updateStoreGeofence,
		arg.Latitude,
		arg.Longitude,
		arg.RadiusMeters,
		arg.ID,
		arg.ExpectedUpdatedAt,
	)
	var i Store
	err := row.Scan(
		&i.ID,
		&i.OdooStoreID,
		&i.StoreName,
		&i.City,
		&i.Latitude,
		&i.Longitude,
		&i.RadiusMeters,
		&i.WifiWhitelistEnabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertEmployees = `-- name: UpsertEmployees :many
UPDATE employees
SET full_name = data.full_name,
    email = data.email,
    updated_at = now()
FROM (
    SELECT unnest($1::bigint[]) AS odoo_employee_id,
           unnest($2::varchar[]) AS full_name,
           unnest($3::citext[]) AS email
) AS data
WHERE employees.odoo_employee_id = data.odoo_employee_id
RETURNING employees.id, employees.odoo_employee_id, false AS inserted
`

type UpsertEmployeesParams struct {
	OdooEmployeeIds []int64  `json:"odoo_employee_ids"`
	FullNames       []string `json:"full_names"`
	Emails          []string `json:"emails"`
}

type UpsertEmployeesRow struct {
	ID             int64 `json:"id"`
	OdooEmployeeID int64 `json:"odoo_employee_id"`
	Inserted       bool  `json:"inserted"`
}

// Bulk-updates one batch of Odoo employees (at most 50, see
// employees.syncEmployeesParams) in a single round trip. Update-only, by
// design (see ADR-0008/ADR-0009): an odoo_employee_id with no matching row
// — not yet admin-created, or deleted since this batch was fetched from
// Odoo — is silently ignored rather than inserted, so sync can never
// (re)create an employee row (which would otherwise need a placeholder,
// Odoo-blind username). Only CreateEmployee ever inserts a row.
func (q *Queries) UpsertEmployees(ctx context.Context, arg UpsertEmployeesParams) ([]UpsertEmployeesRow, error) {
	rows, err := q.db.Query(ctx, upsertEmployees, arg.OdooEmployeeIds, arg.FullNames, arg.Emails)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UpsertEmployeesRow
	for rows.Next() {
		var i UpsertEmployeesRow
		if err := rows.Scan(&i.ID, &i.OdooEmployeeID, &i.Inserted); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertSession = `-- name: UpsertSession :one
INSERT INTO sessions (employee_id, store_id, token_hash, expires_at)
VALUES ($1, $2, $3, $4)
ON CONFLICT (employee_id) DO UPDATE
SET store_id = EXCLUDED.store_id,
    token_hash = EXCLUDED.token_hash,
    issued_at = now(),
    expires_at = EXCLUDED.expires_at,
    last_heartbeat_at = now(),
    consecutive_failures = 0
RETURNING id, employee_id, store_id, token_hash, issued_at, expires_at, last_heartbeat_at, consecutive_failures
`

type UpsertSessionParams struct {
	EmployeeID int64              `json:"employee_id"`
	StoreID    pgtype.Int8        `json:"store_id"`
	TokenHash  string             `json:"token_hash"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
}

// Login's single-active-Session write (ADR-0014): inserts a new Session for
// employee_id, or, if one already exists (UNIQUE employee_id), atomically
// replaces it in place — the "a new Login invalidates any Session already
// open for that Employee" rule, in one round trip rather than a
// delete-then-insert. On the DO UPDATE path, last_heartbeat_at/
// consecutive_failures are reset explicitly (the INSERT path already gets
// them from the column defaults) — a re-issued Session for an Employee who
// had one open before starts Heartbeat's silence/failure tracking clean,
// not carrying over the old Session's state (issue #23).
func (q *Queries) UpsertSession(ctx context.Context, arg UpsertSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, upsertSession,
		arg.EmployeeID,
		arg.StoreID,
		arg.TokenHash,
		arg.ExpiresAt,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.EmployeeID,
		&i.StoreID,
		&i.TokenHash,
		&i.IssuedAt,
		&i.ExpiresAt,
		&i.LastHeartbeatAt,
		&i.ConsecutiveFailures,
	)
	return i, err
}

const upsertStores = `-- name: UpsertStores :many
INSERT INTO store (odoo_store_id, store_name)
SELECT unnest($1::varchar[]), unnest($2::varchar[])
ON CONFLICT (odoo_store_id) DO UPDATE
SET store_name = EXCLUDED.store_name,
    updated_at = CASE
        WHEN store.store_name IS DISTINCT FROM EXCLUDED.store_name
        THEN now()
        ELSE store.updated_at
    END
RETURNING id, odoo_store_id, (xmax = 0) AS inserted
`

type UpsertStoresParams struct {
	OdooStoreIds []string `json:"odoo_store_ids"`
	StoreNames   []string `json:"store_names"`
}

type UpsertStoresRow struct {
	ID          int64       `json:"id"`
	OdooStoreID pgtype.Text `json:"odoo_store_id"`
	Inserted    bool        `json:"inserted"`
}

// Bulk-upserts one page of Odoo stores in a single round trip. "(xmax = 0)"
// is Postgres' standard trick for distinguishing an INSERT from an
// ON CONFLICT UPDATE in the same statement: xmax is only set by an UPDATE,
// so a fresh row's xmax is 0. The store-sync service uses it to report
// inserted_stores vs updated_stores without a second query. updated_at only
// advances when store_name actually changed — store.updated_at also
// doubles as the admin-facing optimistic-lock version for the whole store
// aggregate, so a sync run that finds no real change must not invalidate a
// concurrently-in-flight admin edit's lock token. city isn't part of this
// upsert at all: Odoo's pos.shop model has no city field yet, so sync must
// not touch (and blank out) whatever city a store already has locally.
func (q *Queries) UpsertStores(ctx context.Context, arg UpsertStoresParams) ([]UpsertStoresRow, error) {
	rows, err := q.db.Query(ctx, upsertStores, arg.OdooStoreIds, arg.StoreNames)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UpsertStoresRow
	for rows.Next() {
		var i UpsertStoresRow
		if err := rows.Scan(&i.ID, &i.OdooStoreID, &i.Inserted); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
