// Code generated by MockGen. DO NOT EDIT.
// Source: querier.go
//
// Generated by this command:
//
//	mockgen -source=querier.go -destination=mocks/mock_querier.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	repo "github.com/Bang-Bien-Holding/bangnails.employee-app-backend/internal/adapters/postgresql/sqlc"
	gomock "go.uber.org/mock/gomock"
)

// MockQuerier is a mock of Querier interface.
type MockQuerier struct {
	ctrl     *gomock.Controller
	recorder *MockQuerierMockRecorder
	isgomock struct{}
}

// MockQuerierMockRecorder is the mock recorder for MockQuerier.
type MockQuerierMockRecorder struct {
	mock *MockQuerier
}

// NewMockQuerier creates a new mock instance.
func NewMockQuerier(ctrl *gomock.Controller) *MockQuerier {
	mock := &MockQuerier{ctrl: ctrl}
	mock.recorder = &MockQuerierMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockQuerier) EXPECT() *MockQuerierMockRecorder {
	return m.recorder
}

// CreateEmployee mocks base method.
func (m *MockQuerier) CreateEmployee(ctx context.Context, arg repo.CreateEmployeeParams) (repo.Employee, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateEmployee", ctx, arg)
	ret0, _ := ret[0].(repo.Employee)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateEmployee indicates an expected call of CreateEmployee.
func (mr *MockQuerierMockRecorder) CreateEmployee(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateEmployee", reflect.TypeOf((*MockQuerier)(nil).CreateEmployee), ctx, arg)
}

// CreatePasswordResetToken mocks base method.
func (m *MockQuerier) CreatePasswordResetToken(ctx context.Context, arg repo.CreatePasswordResetTokenParams) (repo.PasswordResetToken, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePasswordResetToken", ctx, arg)
	ret0, _ := ret[0].(repo.PasswordResetToken)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreatePasswordResetToken indicates an expected call of CreatePasswordResetToken.
func (mr *MockQuerierMockRecorder) CreatePasswordResetToken(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePasswordResetToken", reflect.TypeOf((*MockQuerier)(nil).CreatePasswordResetToken), ctx, arg)
}

// DeleteEmployee mocks base method.
func (m *MockQuerier) DeleteEmployee(ctx context.Context, id int64) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteEmployee", ctx, id)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteEmployee indicates an expected call of DeleteEmployee.
func (mr *MockQuerierMockRecorder) DeleteEmployee(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteEmployee", reflect.TypeOf((*MockQuerier)(nil).DeleteEmployee), ctx, id)
}

// GetEmployeeByEmail mocks base method.
func (m *MockQuerier) GetEmployeeByEmail(ctx context.Context, email string) (repo.Employee, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEmployeeByEmail", ctx, email)
	ret0, _ := ret[0].(repo.Employee)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEmployeeByEmail indicates an expected call of GetEmployeeByEmail.
func (mr *MockQuerierMockRecorder) GetEmployeeByEmail(ctx, email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEmployeeByEmail", reflect.TypeOf((*MockQuerier)(nil).GetEmployeeByEmail), ctx, email)
}

// GetEmployeeByID mocks base method.
func (m *MockQuerier) GetEmployeeByID(ctx context.Context, id int64) (repo.Employee, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEmployeeByID", ctx, id)
	ret0, _ := ret[0].(repo.Employee)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEmployeeByID indicates an expected call of GetEmployeeByID.
func (mr *MockQuerierMockRecorder) GetEmployeeByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEmployeeByID", reflect.TypeOf((*MockQuerier)(nil).GetEmployeeByID), ctx, id)
}

// GetEmployeeByUsername mocks base method.
func (m *MockQuerier) GetEmployeeByUsername(ctx context.Context, username string) (repo.Employee, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEmployeeByUsername", ctx, username)
	ret0, _ := ret[0].(repo.Employee)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEmployeeByUsername indicates an expected call of GetEmployeeByUsername.
func (mr *MockQuerierMockRecorder) GetEmployeeByUsername(ctx, username any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEmployeeByUsername", reflect.TypeOf((*MockQuerier)(nil).GetEmployeeByUsername), ctx, username)
}

// GetValidPasswordResetToken mocks base method.
func (m *MockQuerier) GetValidPasswordResetToken(ctx context.Context, token string) (repo.PasswordResetToken, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetValidPasswordResetToken", ctx, token)
	ret0, _ := ret[0].(repo.PasswordResetToken)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetValidPasswordResetToken indicates an expected call of GetValidPasswordResetToken.
func (mr *MockQuerierMockRecorder) GetValidPasswordResetToken(ctx, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetValidPasswordResetToken", reflect.TypeOf((*MockQuerier)(nil).GetValidPasswordResetToken), ctx, token)
}

// ListEmployees mocks base method.
func (m *MockQuerier) ListEmployees(ctx context.Context) ([]repo.Employee, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListEmployees", ctx)
	ret0, _ := ret[0].([]repo.Employee)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListEmployees indicates an expected call of ListEmployees.
func (mr *MockQuerierMockRecorder) ListEmployees(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListEmployees", reflect.TypeOf((*MockQuerier)(nil).ListEmployees), ctx)
}

// MarkPasswordResetTokenUsed mocks base method.
func (m *MockQuerier) MarkPasswordResetTokenUsed(ctx context.Context, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkPasswordResetTokenUsed", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkPasswordResetTokenUsed indicates an expected call of MarkPasswordResetTokenUsed.
func (mr *MockQuerierMockRecorder) MarkPasswordResetTokenUsed(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkPasswordResetTokenUsed", reflect.TypeOf((*MockQuerier)(nil).MarkPasswordResetTokenUsed), ctx, id)
}

// SetEmployeeActive mocks base method.
func (m *MockQuerier) SetEmployeeActive(ctx context.Context, arg repo.SetEmployeeActiveParams) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetEmployeeActive", ctx, arg)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SetEmployeeActive indicates an expected call of SetEmployeeActive.
func (mr *MockQuerierMockRecorder) SetEmployeeActive(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetEmployeeActive", reflect.TypeOf((*MockQuerier)(nil).SetEmployeeActive), ctx, arg)
}

// SetEmployeePassword mocks base method.
func (m *MockQuerier) SetEmployeePassword(ctx context.Context, arg repo.SetEmployeePasswordParams) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetEmployeePassword", ctx, arg)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SetEmployeePassword indicates an expected call of SetEmployeePassword.
func (mr *MockQuerierMockRecorder) SetEmployeePassword(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetEmployeePassword", reflect.TypeOf((*MockQuerier)(nil).SetEmployeePassword), ctx, arg)
}

// UpdateEmployee mocks base method.
func (m *MockQuerier) UpdateEmployee(ctx context.Context, arg repo.UpdateEmployeeParams) (repo.Employee, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateEmployee", ctx, arg)
	ret0, _ := ret[0].(repo.Employee)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateEmployee indicates an expected call of UpdateEmployee.
func (mr *MockQuerierMockRecorder) UpdateEmployee(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateEmployee", reflect.TypeOf((*MockQuerier)(nil).UpdateEmployee), ctx, arg)
}
