// Code generated by MockGen. DO NOT EDIT.
// Source: querier.go
//
// Generated by this command:
//
//	mockgen -source=querier.go -destination=mocks/mock_querier.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	net "net"
	netip "net/netip"
	reflect "reflect"

	repo "github.com/Bang-Bien-Holding/bangnails.employee-app-backend/internal/adapters/postgresql/sqlc"
	gomock "go.uber.org/mock/gomock"
)

// MockQuerier is a mock of Querier interface.
type MockQuerier struct {
	ctrl     *gomock.Controller
	recorder *MockQuerierMockRecorder
	isgomock struct{}
}

// MockQuerierMockRecorder is the mock recorder for MockQuerier.
type MockQuerierMockRecorder struct {
	mock *MockQuerier
}

// NewMockQuerier creates a new mock instance.
func NewMockQuerier(ctrl *gomock.Controller) *MockQuerier {
	mock := &MockQuerier{ctrl: ctrl}
	mock.recorder = &MockQuerierMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockQuerier) EXPECT() *MockQuerierMockRecorder {
	return m.recorder
}

// BulkSetStoreWifiWhitelistEnabled mocks base method.
func (m *MockQuerier) BulkSetStoreWifiWhitelistEnabled(ctx context.Context, arg repo.BulkSetStoreWifiWhitelistEnabledParams) ([]repo.BulkSetStoreWifiWhitelistEnabledRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BulkSetStoreWifiWhitelistEnabled", ctx, arg)
	ret0, _ := ret[0].([]repo.BulkSetStoreWifiWhitelistEnabledRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BulkSetStoreWifiWhitelistEnabled indicates an expected call of BulkSetStoreWifiWhitelistEnabled.
func (mr *MockQuerierMockRecorder) BulkSetStoreWifiWhitelistEnabled(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BulkSetStoreWifiWhitelistEnabled", reflect.TypeOf((*MockQuerier)(nil).BulkSetStoreWifiWhitelistEnabled), ctx, arg)
}

// CountEmployeesByIDs mocks base method.
func (m *MockQuerier) CountEmployeesByIDs(ctx context.Context, ids []int64) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountEmployeesByIDs", ctx, ids)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountEmployeesByIDs indicates an expected call of CountEmployeesByIDs.
func (mr *MockQuerierMockRecorder) CountEmployeesByIDs(ctx, ids any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountEmployeesByIDs", reflect.TypeOf((*MockQuerier)(nil).CountEmployeesByIDs), ctx, ids)
}

// CountPositionsByIDs mocks base method.
func (m *MockQuerier) CountPositionsByIDs(ctx context.Context, ids []int64) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountPositionsByIDs", ctx, ids)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountPositionsByIDs indicates an expected call of CountPositionsByIDs.
func (mr *MockQuerierMockRecorder) CountPositionsByIDs(ctx, ids any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountPositionsByIDs", reflect.TypeOf((*MockQuerier)(nil).CountPositionsByIDs), ctx, ids)
}

// CreateEmployee mocks base method.
func (m *MockQuerier) CreateEmployee(ctx context.Context, arg repo.CreateEmployeeParams) (repo.Employee, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateEmployee", ctx, arg)
	ret0, _ := ret[0].(repo.Employee)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateEmployee indicates an expected call of CreateEmployee.
func (mr *MockQuerierMockRecorder) CreateEmployee(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateEmployee", reflect.TypeOf((*MockQuerier)(nil).CreateEmployee), ctx, arg)
}

// CreatePasswordResetToken mocks base method.
func (m *MockQuerier) CreatePasswordResetToken(ctx context.Context, arg repo.CreatePasswordResetTokenParams) (repo.PasswordResetToken, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePasswordResetToken", ctx, arg)
	ret0, _ := ret[0].(repo.PasswordResetToken)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreatePasswordResetToken indicates an expected call of CreatePasswordResetToken.
func (mr *MockQuerierMockRecorder) CreatePasswordResetToken(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePasswordResetToken", reflect.TypeOf((*MockQuerier)(nil).CreatePasswordResetToken), ctx, arg)
}

// CreatePosition mocks base method.
func (m *MockQuerier) CreatePosition(ctx context.Context, name string) (repo.Position, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePosition", ctx, name)
	ret0, _ := ret[0].(repo.Position)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreatePosition indicates an expected call of CreatePosition.
func (mr *MockQuerierMockRecorder) CreatePosition(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePosition", reflect.TypeOf((*MockQuerier)(nil).CreatePosition), ctx, name)
}

// DeleteEmployee mocks base method.
func (m *MockQuerier) DeleteEmployee(ctx context.Context, id int64) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteEmployee", ctx, id)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteEmployee indicates an expected call of DeleteEmployee.
func (mr *MockQuerierMockRecorder) DeleteEmployee(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteEmployee", reflect.TypeOf((*MockQuerier)(nil).DeleteEmployee), ctx, id)
}

// DeleteEmployeePositionsByPositionIDNotIn mocks base method.
func (m *MockQuerier) DeleteEmployeePositionsByPositionIDNotIn(ctx context.Context, arg repo.DeleteEmployeePositionsByPositionIDNotInParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteEmployeePositionsByPositionIDNotIn", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteEmployeePositionsByPositionIDNotIn indicates an expected call of DeleteEmployeePositionsByPositionIDNotIn.
func (mr *MockQuerierMockRecorder) DeleteEmployeePositionsByPositionIDNotIn(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteEmployeePositionsByPositionIDNotIn", reflect.TypeOf((*MockQuerier)(nil).DeleteEmployeePositionsByPositionIDNotIn), ctx, arg)
}

// DeleteEmployeePositionsNotIn mocks base method.
func (m *MockQuerier) DeleteEmployeePositionsNotIn(ctx context.Context, arg repo.DeleteEmployeePositionsNotInParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteEmployeePositionsNotIn", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteEmployeePositionsNotIn indicates an expected call of DeleteEmployeePositionsNotIn.
func (mr *MockQuerierMockRecorder) DeleteEmployeePositionsNotIn(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteEmployeePositionsNotIn", reflect.TypeOf((*MockQuerier)(nil).DeleteEmployeePositionsNotIn), ctx, arg)
}

// DeleteEmployeeStoresNotIn mocks base method.
func (m *MockQuerier) DeleteEmployeeStoresNotIn(ctx context.Context, arg repo.DeleteEmployeeStoresNotInParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteEmployeeStoresNotIn", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteEmployeeStoresNotIn indicates an expected call of DeleteEmployeeStoresNotIn.
func (mr *MockQuerierMockRecorder) DeleteEmployeeStoresNotIn(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteEmployeeStoresNotIn", reflect.TypeOf((*MockQuerier)(nil).DeleteEmployeeStoresNotIn), ctx, arg)
}

// DeletePosition mocks base method.
func (m *MockQuerier) DeletePosition(ctx context.Context, id int64) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeletePosition", ctx, id)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeletePosition indicates an expected call of DeletePosition.
func (mr *MockQuerierMockRecorder) DeletePosition(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeletePosition", reflect.TypeOf((*MockQuerier)(nil).DeletePosition), ctx, id)
}

// DeletePositions mocks base method.
func (m *MockQuerier) DeletePositions(ctx context.Context, ids []int64) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeletePositions", ctx, ids)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeletePositions indicates an expected call of DeletePositions.
func (mr *MockQuerierMockRecorder) DeletePositions(ctx, ids any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeletePositions", reflect.TypeOf((*MockQuerier)(nil).DeletePositions), ctx, ids)
}

// DeleteSessionByTokenHash mocks base method.
func (m *MockQuerier) DeleteSessionByTokenHash(ctx context.Context, tokenHash string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteSessionByTokenHash", ctx, tokenHash)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteSessionByTokenHash indicates an expected call of DeleteSessionByTokenHash.
func (mr *MockQuerierMockRecorder) DeleteSessionByTokenHash(ctx, tokenHash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteSessionByTokenHash", reflect.TypeOf((*MockQuerier)(nil).DeleteSessionByTokenHash), ctx, tokenHash)
}

// DeleteStoreWifiIPsByValue mocks base method.
func (m *MockQuerier) DeleteStoreWifiIPsByValue(ctx context.Context, arg repo.DeleteStoreWifiIPsByValueParams) ([]netip.Addr, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteStoreWifiIPsByValue", ctx, arg)
	ret0, _ := ret[0].([]netip.Addr)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteStoreWifiIPsByValue indicates an expected call of DeleteStoreWifiIPsByValue.
func (mr *MockQuerierMockRecorder) DeleteStoreWifiIPsByValue(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteStoreWifiIPsByValue", reflect.TypeOf((*MockQuerier)(nil).DeleteStoreWifiIPsByValue), ctx, arg)
}

// DeleteStoreWifiIPsNotIn mocks base method.
func (m *MockQuerier) DeleteStoreWifiIPsNotIn(ctx context.Context, arg repo.DeleteStoreWifiIPsNotInParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteStoreWifiIPsNotIn", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteStoreWifiIPsNotIn indicates an expected call of DeleteStoreWifiIPsNotIn.
func (mr *MockQuerierMockRecorder) DeleteStoreWifiIPsNotIn(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteStoreWifiIPsNotIn", reflect.TypeOf((*MockQuerier)(nil).DeleteStoreWifiIPsNotIn), ctx, arg)
}

// DeleteStoreWifiMacsByValue mocks base method.
func (m *MockQuerier) DeleteStoreWifiMacsByValue(ctx context.Context, arg repo.DeleteStoreWifiMacsByValueParams) ([]net.HardwareAddr, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteStoreWifiMacsByValue", ctx, arg)
	ret0, _ := ret[0].([]net.HardwareAddr)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteStoreWifiMacsByValue indicates an expected call of DeleteStoreWifiMacsByValue.
func (mr *MockQuerierMockRecorder) DeleteStoreWifiMacsByValue(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteStoreWifiMacsByValue", reflect.TypeOf((*MockQuerier)(nil).DeleteStoreWifiMacsByValue), ctx, arg)
}

// DeleteStoreWifiMacsNotIn mocks base method.
func (m *MockQuerier) DeleteStoreWifiMacsNotIn(ctx context.Context, arg repo.DeleteStoreWifiMacsNotInParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteStoreWifiMacsNotIn", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteStoreWifiMacsNotIn indicates an expected call of DeleteStoreWifiMacsNotIn.
func (mr *MockQuerierMockRecorder) DeleteStoreWifiMacsNotIn(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteStoreWifiMacsNotIn", reflect.TypeOf((*MockQuerier)(nil).DeleteStoreWifiMacsNotIn), ctx, arg)
}

// DeleteStores mocks base method.
func (m *MockQuerier) DeleteStores(ctx context.Context, storeIds []int64) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteStores", ctx, storeIds)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteStores indicates an expected call of DeleteStores.
func (mr *MockQuerierMockRecorder) DeleteStores(ctx, storeIds any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteStores", reflect.TypeOf((*MockQuerier)(nil).DeleteStores), ctx, storeIds)
}

// FindStoresNotInOdoo mocks base method.
func (m *MockQuerier) FindStoresNotInOdoo(ctx context.Context, activeOdooStoreIds []string) ([]int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindStoresNotInOdoo", ctx, activeOdooStoreIds)
	ret0, _ := ret[0].([]int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindStoresNotInOdoo indicates an expected call of FindStoresNotInOdoo.
func (mr *MockQuerierMockRecorder) FindStoresNotInOdoo(ctx, activeOdooStoreIds any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindStoresNotInOdoo", reflect.TypeOf((*MockQuerier)(nil).FindStoresNotInOdoo), ctx, activeOdooStoreIds)
}

// GetEmployeeByEmail mocks base method.
func (m *MockQuerier) GetEmployeeByEmail(ctx context.Context, email string) (repo.Employee, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEmployeeByEmail", ctx, email)
	ret0, _ := ret[0].(repo.Employee)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEmployeeByEmail indicates an expected call of GetEmployeeByEmail.
func (mr *MockQuerierMockRecorder) GetEmployeeByEmail(ctx, email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEmployeeByEmail", reflect.TypeOf((*MockQuerier)(nil).GetEmployeeByEmail), ctx, email)
}

// GetEmployeeByID mocks base method.
func (m *MockQuerier) GetEmployeeByID(ctx context.Context, id int64) (repo.Employee, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEmployeeByID", ctx, id)
	ret0, _ := ret[0].(repo.Employee)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEmployeeByID indicates an expected call of GetEmployeeByID.
func (mr *MockQuerierMockRecorder) GetEmployeeByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEmployeeByID", reflect.TypeOf((*MockQuerier)(nil).GetEmployeeByID), ctx, id)
}

// GetEmployeeByUsername mocks base method.
func (m *MockQuerier) GetEmployeeByUsername(ctx context.Context, username string) (repo.Employee, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEmployeeByUsername", ctx, username)
	ret0, _ := ret[0].(repo.Employee)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEmployeeByUsername indicates an expected call of GetEmployeeByUsername.
func (mr *MockQuerierMockRecorder) GetEmployeeByUsername(ctx, username any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEmployeeByUsername", reflect.TypeOf((*MockQuerier)(nil).GetEmployeeByUsername), ctx, username)
}

// GetPositionByID mocks base method.
func (m *MockQuerier) GetPositionByID(ctx context.Context, id int64) (repo.Position, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPositionByID", ctx, id)
	ret0, _ := ret[0].(repo.Position)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPositionByID indicates an expected call of GetPositionByID.
func (mr *MockQuerierMockRecorder) GetPositionByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPositionByID", reflect.TypeOf((*MockQuerier)(nil).GetPositionByID), ctx, id)
}

// GetSessionByTokenHash mocks base method.
func (m *MockQuerier) GetSessionByTokenHash(ctx context.Context, tokenHash string) (repo.Session, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSessionByTokenHash", ctx, tokenHash)
	ret0, _ := ret[0].(repo.Session)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSessionByTokenHash indicates an expected call of GetSessionByTokenHash.
func (mr *MockQuerierMockRecorder) GetSessionByTokenHash(ctx, tokenHash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSessionByTokenHash", reflect.TypeOf((*MockQuerier)(nil).GetSessionByTokenHash), ctx, tokenHash)
}

// GetStoreByID mocks base method.
func (m *MockQuerier) GetStoreByID(ctx context.Context, id int64) (repo.Store, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStoreByID", ctx, id)
	ret0, _ := ret[0].(repo.Store)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStoreByID indicates an expected call of GetStoreByID.
func (mr *MockQuerierMockRecorder) GetStoreByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStoreByID", reflect.TypeOf((*MockQuerier)(nil).GetStoreByID), ctx, id)
}

// GetStoresByIDsForUpdate mocks base method.
func (m *MockQuerier) GetStoresByIDsForUpdate(ctx context.Context, storeIds []int64) ([]repo.GetStoresByIDsForUpdateRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStoresByIDsForUpdate", ctx, storeIds)
	ret0, _ := ret[0].([]repo.GetStoresByIDsForUpdateRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStoresByIDsForUpdate indicates an expected call of GetStoresByIDsForUpdate.
func (mr *MockQuerierMockRecorder) GetStoresByIDsForUpdate(ctx, storeIds any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStoresByIDsForUpdate", reflect.TypeOf((*MockQuerier)(nil).GetStoresByIDsForUpdate), ctx, storeIds)
}

// InsertEmployeePositions mocks base method.
func (m *MockQuerier) InsertEmployeePositions(ctx context.Context, arg repo.InsertEmployeePositionsParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertEmployeePositions", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// InsertEmployeePositions indicates an expected call of InsertEmployeePositions.
func (mr *MockQuerierMockRecorder) InsertEmployeePositions(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertEmployeePositions", reflect.TypeOf((*MockQuerier)(nil).InsertEmployeePositions), ctx, arg)
}

// InsertEmployeeStores mocks base method.
func (m *MockQuerier) InsertEmployeeStores(ctx context.Context, arg repo.InsertEmployeeStoresParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertEmployeeStores", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// InsertEmployeeStores indicates an expected call of InsertEmployeeStores.
func (mr *MockQuerierMockRecorder) InsertEmployeeStores(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertEmployeeStores", reflect.TypeOf((*MockQuerier)(nil).InsertEmployeeStores), ctx, arg)
}

// InsertPositionEmployees mocks base method.
func (m *MockQuerier) InsertPositionEmployees(ctx context.Context, arg repo.InsertPositionEmployeesParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertPositionEmployees", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// InsertPositionEmployees indicates an expected call of InsertPositionEmployees.
func (mr *MockQuerierMockRecorder) InsertPositionEmployees(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertPositionEmployees", reflect.TypeOf((*MockQuerier)(nil).InsertPositionEmployees), ctx, arg)
}

// InsertStoreWifiIPs mocks base method.
func (m *MockQuerier) InsertStoreWifiIPs(ctx context.Context, arg repo.InsertStoreWifiIPsParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertStoreWifiIPs", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// InsertStoreWifiIPs indicates an expected call of InsertStoreWifiIPs.
func (mr *MockQuerierMockRecorder) InsertStoreWifiIPs(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertStoreWifiIPs", reflect.TypeOf((*MockQuerier)(nil).InsertStoreWifiIPs), ctx, arg)
}

// InsertStoreWifiMacs mocks base method.
func (m *MockQuerier) InsertStoreWifiMacs(ctx context.Context, arg repo.InsertStoreWifiMacsParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertStoreWifiMacs", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// InsertStoreWifiMacs indicates an expected call of InsertStoreWifiMacs.
func (mr *MockQuerierMockRecorder) InsertStoreWifiMacs(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertStoreWifiMacs", reflect.TypeOf((*MockQuerier)(nil).InsertStoreWifiMacs), ctx, arg)
}

// InvalidatePasswordResetTokensByEmployeeID mocks base method.
func (m *MockQuerier) InvalidatePasswordResetTokensByEmployeeID(ctx context.Context, employeeID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InvalidatePasswordResetTokensByEmployeeID", ctx, employeeID)
	ret0, _ := ret[0].(error)
	return ret0
}

// InvalidatePasswordResetTokensByEmployeeID indicates an expected call of InvalidatePasswordResetTokensByEmployeeID.
func (mr *MockQuerierMockRecorder) InvalidatePasswordResetTokensByEmployeeID(ctx, employeeID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InvalidatePasswordResetTokensByEmployeeID", reflect.TypeOf((*MockQuerier)(nil).InvalidatePasswordResetTokensByEmployeeID), ctx, employeeID)
}

// IsEmployeeAdmin mocks base method.
func (m *MockQuerier) IsEmployeeAdmin(ctx context.Context, employeeID int64) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsEmployeeAdmin", ctx, employeeID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsEmployeeAdmin indicates an expected call of IsEmployeeAdmin.
func (mr *MockQuerierMockRecorder) IsEmployeeAdmin(ctx, employeeID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsEmployeeAdmin", reflect.TypeOf((*MockQuerier)(nil).IsEmployeeAdmin), ctx, employeeID)
}

// ListEmployeeIDsByIDs mocks base method.
func (m *MockQuerier) ListEmployeeIDsByIDs(ctx context.Context, ids []int64) ([]int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListEmployeeIDsByIDs", ctx, ids)
	ret0, _ := ret[0].([]int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListEmployeeIDsByIDs indicates an expected call of ListEmployeeIDsByIDs.
func (mr *MockQuerierMockRecorder) ListEmployeeIDsByIDs(ctx, ids any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListEmployeeIDsByIDs", reflect.TypeOf((*MockQuerier)(nil).ListEmployeeIDsByIDs), ctx, ids)
}

// ListEmployees mocks base method.
func (m *MockQuerier) ListEmployees(ctx context.Context, arg repo.ListEmployeesParams) ([]repo.Employee, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListEmployees", ctx, arg)
	ret0, _ := ret[0].([]repo.Employee)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListEmployees indicates an expected call of ListEmployees.
func (mr *MockQuerierMockRecorder) ListEmployees(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListEmployees", reflect.TypeOf((*MockQuerier)(nil).ListEmployees), ctx, arg)
}

// ListEmployeesByPositionID mocks base method.
func (m *MockQuerier) ListEmployeesByPositionID(ctx context.Context, positionID int64) ([]repo.Employee, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListEmployeesByPositionID", ctx, positionID)
	ret0, _ := ret[0].([]repo.Employee)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListEmployeesByPositionID indicates an expected call of ListEmployeesByPositionID.
func (mr *MockQuerierMockRecorder) ListEmployeesByPositionID(ctx, positionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListEmployeesByPositionID", reflect.TypeOf((*MockQuerier)(nil).ListEmployeesByPositionID), ctx, positionID)
}

// ListPositionIDsByEmployeeID mocks base method.
func (m *MockQuerier) ListPositionIDsByEmployeeID(ctx context.Context, employeeID int64) ([]int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListPositionIDsByEmployeeID", ctx, employeeID)
	ret0, _ := ret[0].([]int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListPositionIDsByEmployeeID indicates an expected call of ListPositionIDsByEmployeeID.
func (mr *MockQuerierMockRecorder) ListPositionIDsByEmployeeID(ctx, employeeID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListPositionIDsByEmployeeID", reflect.TypeOf((*MockQuerier)(nil).ListPositionIDsByEmployeeID), ctx, employeeID)
}

// ListPositionIDsByEmployeeIDs mocks base method.
func (m *MockQuerier) ListPositionIDsByEmployeeIDs(ctx context.Context, employeeIds []int64) ([]repo.EmployeePosition, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListPositionIDsByEmployeeIDs", ctx, employeeIds)
	ret0, _ := ret[0].([]repo.EmployeePosition)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListPositionIDsByEmployeeIDs indicates an expected call of ListPositionIDsByEmployeeIDs.
func (mr *MockQuerierMockRecorder) ListPositionIDsByEmployeeIDs(ctx, employeeIds any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListPositionIDsByEmployeeIDs", reflect.TypeOf((*MockQuerier)(nil).ListPositionIDsByEmployeeIDs), ctx, employeeIds)
}

// ListPositions mocks base method.
func (m *MockQuerier) ListPositions(ctx context.Context) ([]repo.Position, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListPositions", ctx)
	ret0, _ := ret[0].([]repo.Position)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListPositions indicates an expected call of ListPositions.
func (mr *MockQuerierMockRecorder) ListPositions(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListPositions", reflect.TypeOf((*MockQuerier)(nil).ListPositions), ctx)
}

// ListStoreIDsByEmployeeID mocks base method.
func (m *MockQuerier) ListStoreIDsByEmployeeID(ctx context.Context, employeeID int64) ([]int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListStoreIDsByEmployeeID", ctx, employeeID)
	ret0, _ := ret[0].([]int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListStoreIDsByEmployeeID indicates an expected call of ListStoreIDsByEmployeeID.
func (mr *MockQuerierMockRecorder) ListStoreIDsByEmployeeID(ctx, employeeID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListStoreIDsByEmployeeID", reflect.TypeOf((*MockQuerier)(nil).ListStoreIDsByEmployeeID), ctx, employeeID)
}

// ListStoreIDsByEmployeeIDs mocks base method.
func (m *MockQuerier) ListStoreIDsByEmployeeIDs(ctx context.Context, employeeIds []int64) ([]repo.EmployeeStore, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListStoreIDsByEmployeeIDs", ctx, employeeIds)
	ret0, _ := ret[0].([]repo.EmployeeStore)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListStoreIDsByEmployeeIDs indicates an expected call of ListStoreIDsByEmployeeIDs.
func (mr *MockQuerierMockRecorder) ListStoreIDsByEmployeeIDs(ctx, employeeIds any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListStoreIDsByEmployeeIDs", reflect.TypeOf((*MockQuerier)(nil).ListStoreIDsByEmployeeIDs), ctx, employeeIds)
}

// ListStoreWifiIPsByStoreID mocks base method.
func (m *MockQuerier) ListStoreWifiIPsByStoreID(ctx context.Context, storeID int64) ([]netip.Addr, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListStoreWifiIPsByStoreID", ctx, storeID)
	ret0, _ := ret[0].([]netip.Addr)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListStoreWifiIPsByStoreID indicates an expected call of ListStoreWifiIPsByStoreID.
func (mr *MockQuerierMockRecorder) ListStoreWifiIPsByStoreID(ctx, storeID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListStoreWifiIPsByStoreID", reflect.TypeOf((*MockQuerier)(nil).ListStoreWifiIPsByStoreID), ctx, storeID)
}

// ListStoreWifiMacsByStoreID mocks base method.
func (m *MockQuerier) ListStoreWifiMacsByStoreID(ctx context.Context, storeID int64) ([]net.HardwareAddr, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListStoreWifiMacsByStoreID", ctx, storeID)
	ret0, _ := ret[0].([]net.HardwareAddr)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListStoreWifiMacsByStoreID indicates an expected call of ListStoreWifiMacsByStoreID.
func (mr *MockQuerierMockRecorder) ListStoreWifiMacsByStoreID(ctx, storeID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListStoreWifiMacsByStoreID", reflect.TypeOf((*MockQuerier)(nil).ListStoreWifiMacsByStoreID), ctx, storeID)
}

// ListStores mocks base method.
func (m *MockQuerier) ListStores(ctx context.Context, arg repo.ListStoresParams) ([]repo.ListStoresRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListStores", ctx, arg)
	ret0, _ := ret[0].([]repo.ListStoresRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListStores indicates an expected call of ListStores.
func (mr *MockQuerierMockRecorder) ListStores(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListStores", reflect.TypeOf((*MockQuerier)(nil).ListStores), ctx, arg)
}

// ListStoresByOdooStoreIDs mocks base method.
func (m *MockQuerier) ListStoresByOdooStoreIDs(ctx context.Context, odooStoreIds []string) ([]repo.ListStoresByOdooStoreIDsRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListStoresByOdooStoreIDs", ctx, odooStoreIds)
	ret0, _ := ret[0].([]repo.ListStoresByOdooStoreIDsRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListStoresByOdooStoreIDs indicates an expected call of ListStoresByOdooStoreIDs.
func (mr *MockQuerierMockRecorder) ListStoresByOdooStoreIDs(ctx, odooStoreIds any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListStoresByOdooStoreIDs", reflect.TypeOf((*MockQuerier)(nil).ListStoresByOdooStoreIDs), ctx, odooStoreIds)
}

// ListStoresForLoginByEmployeeID mocks base method.
func (m *MockQuerier) ListStoresForLoginByEmployeeID(ctx context.Context, employeeID int64) ([]repo.ListStoresForLoginByEmployeeIDRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListStoresForLoginByEmployeeID", ctx, employeeID)
	ret0, _ := ret[0].([]repo.ListStoresForLoginByEmployeeIDRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListStoresForLoginByEmployeeID indicates an expected call of ListStoresForLoginByEmployeeID.
func (mr *MockQuerierMockRecorder) ListStoresForLoginByEmployeeID(ctx, employeeID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListStoresForLoginByEmployeeID", reflect.TypeOf((*MockQuerier)(nil).ListStoresForLoginByEmployeeID), ctx, employeeID)
}

// RecordFailedLoginAttempt mocks base method.
func (m *MockQuerier) RecordFailedLoginAttempt(ctx context.Context, arg repo.RecordFailedLoginAttemptParams) (repo.Employee, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RecordFailedLoginAttempt", ctx, arg)
	ret0, _ := ret[0].(repo.Employee)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RecordFailedLoginAttempt indicates an expected call of RecordFailedLoginAttempt.
func (mr *MockQuerierMockRecorder) RecordFailedLoginAttempt(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecordFailedLoginAttempt", reflect.TypeOf((*MockQuerier)(nil).RecordFailedLoginAttempt), ctx, arg)
}

// RecordHeartbeatFailure mocks base method.
func (m *MockQuerier) RecordHeartbeatFailure(ctx context.Context, tokenHash string) (repo.Session, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RecordHeartbeatFailure", ctx, tokenHash)
	ret0, _ := ret[0].(repo.Session)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RecordHeartbeatFailure indicates an expected call of RecordHeartbeatFailure.
func (mr *MockQuerierMockRecorder) RecordHeartbeatFailure(ctx, tokenHash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecordHeartbeatFailure", reflect.TypeOf((*MockQuerier)(nil).RecordHeartbeatFailure), ctx, tokenHash)
}

// RecordHeartbeatSuccess mocks base method.
func (m *MockQuerier) RecordHeartbeatSuccess(ctx context.Context, tokenHash string) (repo.Session, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RecordHeartbeatSuccess", ctx, tokenHash)
	ret0, _ := ret[0].(repo.Session)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RecordHeartbeatSuccess indicates an expected call of RecordHeartbeatSuccess.
func (mr *MockQuerierMockRecorder) RecordHeartbeatSuccess(ctx, tokenHash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecordHeartbeatSuccess", reflect.TypeOf((*MockQuerier)(nil).RecordHeartbeatSuccess), ctx, tokenHash)
}

// RedeemPasswordResetToken mocks base method.
func (m *MockQuerier) RedeemPasswordResetToken(ctx context.Context, tokenHash string) (repo.PasswordResetToken, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RedeemPasswordResetToken", ctx, tokenHash)
	ret0, _ := ret[0].(repo.PasswordResetToken)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RedeemPasswordResetToken indicates an expected call of RedeemPasswordResetToken.
func (mr *MockQuerierMockRecorder) RedeemPasswordResetToken(ctx, tokenHash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RedeemPasswordResetToken", reflect.TypeOf((*MockQuerier)(nil).RedeemPasswordResetToken), ctx, tokenHash)
}

// ResetFailedLoginAttempts mocks base method.
func (m *MockQuerier) ResetFailedLoginAttempts(ctx context.Context, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResetFailedLoginAttempts", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// ResetFailedLoginAttempts indicates an expected call of ResetFailedLoginAttempts.
func (mr *MockQuerierMockRecorder) ResetFailedLoginAttempts(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResetFailedLoginAttempts", reflect.TypeOf((*MockQuerier)(nil).ResetFailedLoginAttempts), ctx, id)
}

// SetEmployeeActive mocks base method.
func (m *MockQuerier) SetEmployeeActive(ctx context.Context, arg repo.SetEmployeeActiveParams) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetEmployeeActive", ctx, arg)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SetEmployeeActive indicates an expected call of SetEmployeeActive.
func (mr *MockQuerierMockRecorder) SetEmployeeActive(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetEmployeeActive", reflect.TypeOf((*MockQuerier)(nil).SetEmployeeActive), ctx, arg)
}

// SetEmployeePassword mocks base method.
func (m *MockQuerier) SetEmployeePassword(ctx context.Context, arg repo.SetEmployeePasswordParams) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetEmployeePassword", ctx, arg)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SetEmployeePassword indicates an expected call of SetEmployeePassword.
func (mr *MockQuerierMockRecorder) SetEmployeePassword(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetEmployeePassword", reflect.TypeOf((*MockQuerier)(nil).SetEmployeePassword), ctx, arg)
}

// SetStoreWifiWhitelistEnabled mocks base method.
func (m *MockQuerier) SetStoreWifiWhitelistEnabled(ctx context.Context, arg repo.SetStoreWifiWhitelistEnabledParams) (repo.SetStoreWifiWhitelistEnabledRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetStoreWifiWhitelistEnabled", ctx, arg)
	ret0, _ := ret[0].(repo.SetStoreWifiWhitelistEnabledRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SetStoreWifiWhitelistEnabled indicates an expected call of SetStoreWifiWhitelistEnabled.
func (mr *MockQuerierMockRecorder) SetStoreWifiWhitelistEnabled(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetStoreWifiWhitelistEnabled", reflect.TypeOf((*MockQuerier)(nil).SetStoreWifiWhitelistEnabled), ctx, arg)
}

// UpdateEmployee mocks base method.
func (m *MockQuerier) UpdateEmployee(ctx context.Context, arg repo.UpdateEmployeeParams) (repo.Employee, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateEmployee", ctx, arg)
	ret0, _ := ret[0].(repo.Employee)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateEmployee indicates an expected call of UpdateEmployee.
func (mr *MockQuerierMockRecorder) UpdateEmployee(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateEmployee", reflect.TypeOf((*MockQuerier)(nil).UpdateEmployee), ctx, arg)
}

// UpdatePosition mocks base method.
func (m *MockQuerier) UpdatePosition(ctx context.Context, arg repo.UpdatePositionParams) (repo.Position, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePosition", ctx, arg)
	ret0, _ := ret[0].(repo.Position)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdatePosition indicates an expected call of UpdatePosition.
func (mr *MockQuerierMockRecorder) UpdatePosition(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePosition", reflect.TypeOf((*MockQuerier)(nil).UpdatePosition), ctx, arg)
}

// UpdateStoreGeofence mocks base method.
func (m *MockQuerier) UpdateStoreGeofence(ctx context.Context, arg repo.UpdateStoreGeofenceParams) (repo.Store, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateStoreGeofence", ctx, arg)
	ret0, _ := ret[0].(repo.Store)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateStoreGeofence indicates an expected call of UpdateStoreGeofence.
func (mr *MockQuerierMockRecorder) UpdateStoreGeofence(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateStoreGeofence", reflect.TypeOf((*MockQuerier)(nil).UpdateStoreGeofence), ctx, arg)
}

// UpsertEmployees mocks base method.
func (m *MockQuerier) UpsertEmployees(ctx context.Context, arg repo.UpsertEmployeesParams) ([]repo.UpsertEmployeesRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertEmployees", ctx, arg)
	ret0, _ := ret[0].([]repo.UpsertEmployeesRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpsertEmployees indicates an expected call of UpsertEmployees.
func (mr *MockQuerierMockRecorder) UpsertEmployees(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertEmployees", reflect.TypeOf((*MockQuerier)(nil).UpsertEmployees), ctx, arg)
}

// UpsertSession mocks base method.
func (m *MockQuerier) UpsertSession(ctx context.Context, arg repo.UpsertSessionParams) (repo.Session, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertSession", ctx, arg)
	ret0, _ := ret[0].(repo.Session)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpsertSession indicates an expected call of UpsertSession.
func (mr *MockQuerierMockRecorder) UpsertSession(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertSession", reflect.TypeOf((*MockQuerier)(nil).UpsertSession), ctx, arg)
}

// UpsertStores mocks base method.
func (m *MockQuerier) UpsertStores(ctx context.Context, arg repo.UpsertStoresParams) ([]repo.UpsertStoresRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertStores", ctx, arg)
	ret0, _ := ret[0].([]repo.UpsertStoresRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpsertStores indicates an expected call of UpsertStores.
func (mr *MockQuerierMockRecorder) UpsertStores(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertStores", reflect.TypeOf((*MockQuerier)(nil).UpsertStores), ctx, arg)
}
