// Code generated by MockGen. DO NOT EDIT.
// Source: types.go
//
// Generated by this command:
//
//	mockgen -source=types.go -destination=service_mock_test.go -package=positions
//

// Package positions is a generated GoMock package.
package positions

import (
	context "context"
	reflect "reflect"

	repo "github.com/Bang-Bien-Holding/bangnails.employee-app-backend/internal/adapters/postgresql/sqlc"
	gomock "go.uber.org/mock/gomock"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
	isgomock struct{}
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// CreatePosition mocks base method.
func (m *MockService) CreatePosition(ctx context.Context, params createPositionParams) (repo.Position, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePosition", ctx, params)
	ret0, _ := ret[0].(repo.Position)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreatePosition indicates an expected call of CreatePosition.
func (mr *MockServiceMockRecorder) CreatePosition(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePosition", reflect.TypeOf((*MockService)(nil).CreatePosition), ctx, params)
}

// DeletePosition mocks base method.
func (m *MockService) DeletePosition(ctx context.Context, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeletePosition", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeletePosition indicates an expected call of DeletePosition.
func (mr *MockServiceMockRecorder) DeletePosition(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeletePosition", reflect.TypeOf((*MockService)(nil).DeletePosition), ctx, id)
}

// ListPositions mocks base method.
func (m *MockService) ListPositions(ctx context.Context) ([]repo.Position, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListPositions", ctx)
	ret0, _ := ret[0].([]repo.Position)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListPositions indicates an expected call of ListPositions.
func (mr *MockServiceMockRecorder) ListPositions(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListPositions", reflect.TypeOf((*MockService)(nil).ListPositions), ctx)
}

// UpdatePosition mocks base method.
func (m *MockService) UpdatePosition(ctx context.Context, id int64, params updatePositionParams) (repo.Position, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePosition", ctx, id, params)
	ret0, _ := ret[0].(repo.Position)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdatePosition indicates an expected call of UpdatePosition.
func (mr *MockServiceMockRecorder) UpdatePosition(ctx, id, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePosition", reflect.TypeOf((*MockService)(nil).UpdatePosition), ctx, id, params)
}
