// Code generated by MockGen. DO NOT EDIT.
// Source: client.go
//
// Generated by this command:
//
//	mockgen -source=client.go -destination=mocks/mock_client.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	odoo "github.com/Bang-Bien-Holding/bangnails.employee-app-backend/internal/odoo"
	gomock "go.uber.org/mock/gomock"
)

// MockClient is a mock of Client interface.
type MockClient struct {
	ctrl     *gomock.Controller
	recorder *MockClientMockRecorder
	isgomock struct{}
}

// MockClientMockRecorder is the mock recorder for MockClient.
type MockClientMockRecorder struct {
	mock *MockClient
}

// NewMockClient creates a new mock instance.
func NewMockClient(ctrl *gomock.Controller) *MockClient {
	mock := &MockClient{ctrl: ctrl}
	mock.recorder = &MockClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClient) EXPECT() *MockClientMockRecorder {
	return m.recorder
}

// FetchStores mocks base method.
func (m *MockClient) FetchStores(ctx context.Context, limit, offset int) ([]odoo.Store, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchStores", ctx, limit, offset)
	ret0, _ := ret[0].([]odoo.Store)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchStores indicates an expected call of FetchStores.
func (mr *MockClientMockRecorder) FetchStores(ctx, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchStores", reflect.TypeOf((*MockClient)(nil).FetchStores), ctx, limit, offset)
}
