// Code generated by MockGen. DO NOT EDIT.
// Source: types.go
//
// Generated by this command:
//
//	mockgen -source=types.go -destination=service_mock_test.go -package=employees
//

// Package employees is a generated GoMock package.
package employees

import (
	context "context"
	reflect "reflect"

	repo "github.com/Bang-Bien-Holding/bangnails.employee-app-backend/internal/adapters/postgresql/sqlc"
	gomock "go.uber.org/mock/gomock"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
	isgomock struct{}
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// BulkDeleteEmployees mocks base method.
func (m *MockService) BulkDeleteEmployees(ctx context.Context, ids []int64) []BulkActionResult {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BulkDeleteEmployees", ctx, ids)
	ret0, _ := ret[0].([]BulkActionResult)
	return ret0
}

// BulkDeleteEmployees indicates an expected call of BulkDeleteEmployees.
func (mr *MockServiceMockRecorder) BulkDeleteEmployees(ctx, ids any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BulkDeleteEmployees", reflect.TypeOf((*MockService)(nil).BulkDeleteEmployees), ctx, ids)
}

// BulkSendPasswordResetLinks mocks base method.
func (m *MockService) BulkSendPasswordResetLinks(ctx context.Context, ids []int64) []BulkActionResult {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BulkSendPasswordResetLinks", ctx, ids)
	ret0, _ := ret[0].([]BulkActionResult)
	return ret0
}

// BulkSendPasswordResetLinks indicates an expected call of BulkSendPasswordResetLinks.
func (mr *MockServiceMockRecorder) BulkSendPasswordResetLinks(ctx, ids any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BulkSendPasswordResetLinks", reflect.TypeOf((*MockService)(nil).BulkSendPasswordResetLinks), ctx, ids)
}

// CompleteActivation mocks base method.
func (m *MockService) CompleteActivation(ctx context.Context, params completeActivationParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CompleteActivation", ctx, params)
	ret0, _ := ret[0].(error)
	return ret0
}

// CompleteActivation indicates an expected call of CompleteActivation.
func (mr *MockServiceMockRecorder) CompleteActivation(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CompleteActivation", reflect.TypeOf((*MockService)(nil).CompleteActivation), ctx, params)
}

// CreateEmployee mocks base method.
func (m *MockService) CreateEmployee(ctx context.Context, params createEmployeeParams) (repo.Employee, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateEmployee", ctx, params)
	ret0, _ := ret[0].(repo.Employee)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateEmployee indicates an expected call of CreateEmployee.
func (mr *MockServiceMockRecorder) CreateEmployee(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateEmployee", reflect.TypeOf((*MockService)(nil).CreateEmployee), ctx, params)
}

// DeleteEmployee mocks base method.
func (m *MockService) DeleteEmployee(ctx context.Context, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteEmployee", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteEmployee indicates an expected call of DeleteEmployee.
func (mr *MockServiceMockRecorder) DeleteEmployee(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteEmployee", reflect.TypeOf((*MockService)(nil).DeleteEmployee), ctx, id)
}

// GetEmployeeByID mocks base method.
func (m *MockService) GetEmployeeByID(ctx context.Context, id int64) (repo.Employee, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEmployeeByID", ctx, id)
	ret0, _ := ret[0].(repo.Employee)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEmployeeByID indicates an expected call of GetEmployeeByID.
func (mr *MockServiceMockRecorder) GetEmployeeByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEmployeeByID", reflect.TypeOf((*MockService)(nil).GetEmployeeByID), ctx, id)
}

// ListEmployees mocks base method.
func (m *MockService) ListEmployees(ctx context.Context) ([]repo.Employee, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListEmployees", ctx)
	ret0, _ := ret[0].([]repo.Employee)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListEmployees indicates an expected call of ListEmployees.
func (mr *MockServiceMockRecorder) ListEmployees(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListEmployees", reflect.TypeOf((*MockService)(nil).ListEmployees), ctx)
}

// SetEmployeeActive mocks base method.
func (m *MockService) SetEmployeeActive(ctx context.Context, id int64, isActive bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetEmployeeActive", ctx, id, isActive)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetEmployeeActive indicates an expected call of SetEmployeeActive.
func (mr *MockServiceMockRecorder) SetEmployeeActive(ctx, id, isActive any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetEmployeeActive", reflect.TypeOf((*MockService)(nil).SetEmployeeActive), ctx, id, isActive)
}

// SetEmployeePassword mocks base method.
func (m *MockService) SetEmployeePassword(ctx context.Context, id int64, password string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetEmployeePassword", ctx, id, password)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetEmployeePassword indicates an expected call of SetEmployeePassword.
func (mr *MockServiceMockRecorder) SetEmployeePassword(ctx, id, password any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetEmployeePassword", reflect.TypeOf((*MockService)(nil).SetEmployeePassword), ctx, id, password)
}

// UpdateEmployee mocks base method.
func (m *MockService) UpdateEmployee(ctx context.Context, id int64, params updateEmployeeParams) (repo.Employee, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateEmployee", ctx, id, params)
	ret0, _ := ret[0].(repo.Employee)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateEmployee indicates an expected call of UpdateEmployee.
func (mr *MockServiceMockRecorder) UpdateEmployee(ctx, id, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateEmployee", reflect.TypeOf((*MockService)(nil).UpdateEmployee), ctx, id, params)
}
