// Code generated by MockGen. DO NOT EDIT.
// Source: types.go
//
// Generated by this command:
//
//	mockgen -source=types.go -destination=service_mock_test.go -package=stores
//

// Package stores is a generated GoMock package.
package stores

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
	isgomock struct{}
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// BulkSetWifiWhitelistEnabled mocks base method.
func (m *MockService) BulkSetWifiWhitelistEnabled(ctx context.Context, params bulkSetWifiWhitelistEnabledParams) ([]StoreWifiToggleResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BulkSetWifiWhitelistEnabled", ctx, params)
	ret0, _ := ret[0].([]StoreWifiToggleResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BulkSetWifiWhitelistEnabled indicates an expected call of BulkSetWifiWhitelistEnabled.
func (mr *MockServiceMockRecorder) BulkSetWifiWhitelistEnabled(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BulkSetWifiWhitelistEnabled", reflect.TypeOf((*MockService)(nil).BulkSetWifiWhitelistEnabled), ctx, params)
}

// DeleteWifiWhitelistEntries mocks base method.
func (m *MockService) DeleteWifiWhitelistEntries(ctx context.Context, id int64, params deleteWifiWhitelistParams) ([]WifiWhitelistDeleteResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteWifiWhitelistEntries", ctx, id, params)
	ret0, _ := ret[0].([]WifiWhitelistDeleteResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteWifiWhitelistEntries indicates an expected call of DeleteWifiWhitelistEntries.
func (mr *MockServiceMockRecorder) DeleteWifiWhitelistEntries(ctx, id, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteWifiWhitelistEntries", reflect.TypeOf((*MockService)(nil).DeleteWifiWhitelistEntries), ctx, id, params)
}

// GetStoreByID mocks base method.
func (m *MockService) GetStoreByID(ctx context.Context, id int64) (StoreDetail, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStoreByID", ctx, id)
	ret0, _ := ret[0].(StoreDetail)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStoreByID indicates an expected call of GetStoreByID.
func (mr *MockServiceMockRecorder) GetStoreByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStoreByID", reflect.TypeOf((*MockService)(nil).GetStoreByID), ctx, id)
}

// ListStores mocks base method.
func (m *MockService) ListStores(ctx context.Context) ([]StoreDetail, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListStores", ctx)
	ret0, _ := ret[0].([]StoreDetail)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListStores indicates an expected call of ListStores.
func (mr *MockServiceMockRecorder) ListStores(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListStores", reflect.TypeOf((*MockService)(nil).ListStores), ctx)
}

// SetStoreWifiWhitelistEnabled mocks base method.
func (m *MockService) SetStoreWifiWhitelistEnabled(ctx context.Context, id int64, params setWifiWhitelistEnabledParams) (StoreWifiToggleResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetStoreWifiWhitelistEnabled", ctx, id, params)
	ret0, _ := ret[0].(StoreWifiToggleResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SetStoreWifiWhitelistEnabled indicates an expected call of SetStoreWifiWhitelistEnabled.
func (mr *MockServiceMockRecorder) SetStoreWifiWhitelistEnabled(ctx, id, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetStoreWifiWhitelistEnabled", reflect.TypeOf((*MockService)(nil).SetStoreWifiWhitelistEnabled), ctx, id, params)
}

// SyncStores mocks base method.
func (m *MockService) SyncStores(ctx context.Context) (SyncSummary, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SyncStores", ctx)
	ret0, _ := ret[0].(SyncSummary)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SyncStores indicates an expected call of SyncStores.
func (mr *MockServiceMockRecorder) SyncStores(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SyncStores", reflect.TypeOf((*MockService)(nil).SyncStores), ctx)
}

// UpdateStore mocks base method.
func (m *MockService) UpdateStore(ctx context.Context, id int64, params patchStoreParams) (StoreDetail, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateStore", ctx, id, params)
	ret0, _ := ret[0].(StoreDetail)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateStore indicates an expected call of UpdateStore.
func (mr *MockServiceMockRecorder) UpdateStore(ctx, id, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateStore", reflect.TypeOf((*MockService)(nil).UpdateStore), ctx, id, params)
}
