// Code generated by MockGen. DO NOT EDIT.
// Source: types.go
//
// Generated by this command:
//
//	mockgen -source=types.go -destination=service_mock_test.go -package=stores
//

// Package stores is a generated GoMock package.
package stores

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
	isgomock struct{}
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// SyncStores mocks base method.
func (m *MockService) SyncStores(ctx context.Context) (SyncSummary, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SyncStores", ctx)
	ret0, _ := ret[0].(SyncSummary)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SyncStores indicates an expected call of SyncStores.
func (mr *MockServiceMockRecorder) SyncStores(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SyncStores", reflect.TypeOf((*MockService)(nil).SyncStores), ctx)
}
